### ISSUE TITLE
Can I have these nodes to react to a question posed to Alexa?

### ISSUE THREAD

**Issue by kevdel** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#105]
My use case is this- "Alexa, what is the house summary?" from there I have node-red flows to acquire temperatures, humidity, door status, light status etc.

What I would like to do is return that summary as a text. I can get node-red to speak the summary but I cannot get the request "What is the house summary?" to trigger that speech.

I've looked through examples but I didn't find anything.. Any help appreciated!!

**Comment by smcgann99** [comment]
Lots of info and links in this topic [https://discourse.nodered.org/t/pure-fun-with-alexa-and-alexa-skills/46867](url)
