### ISSUE TITLE
intercept default Alexa response

### ISSUE THREAD

**Issue by tjl694** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#107]
Hey!

Just wondering if there's a way I can intercept (and stop) the default Alexa response for a given phrase?

At the moment, I say a phrase, then Alexa replies with something like "Sorry, I don't know that".

I could create a routine with all my node-red phrases as triggers that does nothing, however it would be great not to have to do that!

**Comment by brunialti** [comment]
You can use node-red-contrib-alexa-smart-home , create a dummy device with the nane that gives you the Alexa message back, of the congruenti type ( if you issue the command " switch off', the type must be switch and so on).
If somebody has other solutions, they are welcome!
