### ISSUE TITLE
Spanish language

### ISSUE THREAD

**Issue by herdkilling** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#11]
I would like to know if it's possible to set the language to spanish.

It's working with spanish words, but it speaks things with a weird english accent (en-US).

**Comment by bbindreiter** [comment]
Do I understand it correctly: Your Alexa is set to Spanish but when you output something using the speak function of the Alexa Routine Node it's English?

**Comment by herdkilling** [comment]
That's correct.


I don't know if spanish is available, I don't see it listed in the table that contains the **Service Host**, **Page** and **Language** and that's why I'm currently using USA | pitangui.amazon.com | amazon.com | en-US.


These are the languages that are currently listed in the setup instructions.

USA | pitangui.amazon.com | amazon.com | en-US
UK | alexa.amazon.co.uk | amazon.co.uk | en-UK
GER | layla.amazon.de | amazon.de | de-DE
ITA | alexa.amazon.it | amazon.it | it-IT
AUS | alexa.amazon.com.au | amazon.com.au | en-US

**Comment by jruizcoll** [comment]
@herdkilling, I get a very good Spanish accent with these settings: alexa.amazon.es | amazon.es | es-ES
Using other settings, I didn't get any sound on my devices, but msg.payload.success = true on Alexa Routine node output, which was very frustrating. Now is working like a charm.
Thank you very much @bbindreiter for your great work. Maybe you can include these settings in the README.md file

**Comment by bbindreiter** [comment]
Thanks! I've added it
