### ISSUE TITLE
Proxy page has no login "Looking for something else? Go to the previous version"

### ISSUE THREAD

**Issue by gregorykau** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#116]
![image](https://user-images.githubusercontent.com/73324666/224480349-54f37377-f49b-4c91-a481-4e2802313f50.png)

This may not be an issue as such, and might just be down to me misunderstanding the initialisation parameters, but I can't get the proxy page to return anything other than this screen. I can't login here to have the cookies retrieved. 

Service host: alexa.amazon.com.au
Page: amazon.com.au

Is this a known issue? 

I am using 5.0.25.

Thanks!

**Comment by bbindreiter** [comment]
Not yet. Thanks for reporting. What happens when you scan and log in via the app? I presume the page should then automatically refresh and the cookie should be picked up.

**Comment by gregorykau** [comment]
Unfortunately not, the qr is just a link to "https://alexa.amazon.com/spa/index.html#v2/home", and is not associated with the page request. 

https://alexa.amazon.com/spa/index.html
Redirects to a login page as expected. But I can't get to this page from the proxy to perform the login which can then (I assume) capture the cookie.

**Comment by bbindreiter** [comment]
Thank you, got it.

Could someone with a AU service host confirm the problem (backup your cookie file first so you can go back to being logged in)?

**Comment by ArekKubacki** [comment]
The same on amazon.com. No chance to log in.

**Comment by bbindreiter** [comment]
Alright. having the same problem now as well. Should be just a redirect/or different landing page url, I will debug it tonight.

**Comment by gregorykau** [comment]
I haven't delved much into alexa-remote2 as of yet, but as a quick personal hack...

alexa-cookie2/lib/proxy.js
Setting Line 138 to... `_options.baseAmazonPag = 'amazon.com.au/spa/index.html'`

Gets past the issue. Don't know about the intermediary layers of how this all comes together.

**Comment by bbindreiter** [comment]
Yes 👍, I will add a PR on alexa-cookie to add `/spa/index.html` to the base url. This lib is used in alexa-remote which is used in applestrudel.

**Comment by gregorykau** [comment]
Gotcha! I should've raised the issue there, but posted on this repository before I bothered to look into it properly. Laziness I'm afraid, hence the want to automate in the first place :D

**Comment by ArekKubacki** [comment]
@gregorykau 
Does the change you provided work? It throws an error for me.

https://alexa.amazon.com/spa/index.html/
HTTP ERROR 404

I think the problem is in the "/" at the end but I can't get rid of it. Are you able to send your alexa-cookie2/lib/proxy.js file? Because in mine in the given line there is something completely different.

**Comment by bbindreiter** [comment]
It's not that easy. I hacked in the `/spa/index.html` appendix into the cookie library but then the proxy, unlike when opening it in the browser directly, gets a cloudfront error back.

**Comment by gregorykau** [comment]
> @gregorykau Does the change you provided work? It throws an error for me.
> 
> https://alexa.amazon.com/spa/index.html/ HTTP ERROR 404
> 
> I think the problem is in the "/" at the end but I can't get rid of it. Are you able to send your alexa-cookie2/lib/proxy.js file? Because in mine in the given line there is something completely different.

This is working for me currently. 

"version": "4.1.3",
**alexa-cookie2\lib\proxy.js** Starting at line 137
```
    let proxyCookies = '';
    
    _options.baseAmazonPag = 'amazon.com.au/spa/index.html';

    // proxy middleware options
    const optionsAlexa = {
````

**Comment by ArekKubacki** [comment]
It is not working for me :(

**Comment by bbindreiter** [comment]
Here's a workaround that has always worked for me so far:

1.) Clear all your cookies from alexa.amazon.com
2.) Restart node-red so you get the `open http://your-hostname:3456` message
3.) Open a new tab and go to `https://alexa.amazon.com/spa/index.html` -> login with your credentials
4.) Open a new tab and open the link that node-red shows -> If you get the page shown as below click on the "Looking for something else?" link in the top left.
5.) Login happens automatically, cookie is fetched and once you see `http://your-hostname:3456/cookie-success` in the URL bar you're all set and can go back to node red.

<img width="998" alt="image" src="https://user-images.githubusercontent.com/3252801/228971580-e7e1393e-3f94-4711-bcdc-f12e9f213a55.png">

**Comment by Apollon77** [comment]
Can noone provide me with a fukll debug log of that? Normally  The / call on the proxy port should directly forward to the Login mask from amazon and not to that alexa.amazon.de page, thats why I would like to understand what happens here

**Comment by bbindreiter** [comment]
Email sent. Thank you!

**Comment by dhodgesnvl** [comment]
Thanks for your work!  I've been working on it for a while but nothing changes.  Which flavor of the node-red-alexa should I be working with?
TIA Doc

**Comment by bbindreiter** [comment]
> Thanks for your work! I've been working on it for a while but nothing changes. Which flavor of the node-red-alexa should I be working with? TIA Doc

https://github.com/Apollon77/alexa-remote and subsequently this uses https://github.com/Apollon77/alexa-cookie.
