### ISSUE TITLE
On device activity working very inconsistently

### ISSUE THREAD

**Issue by obaldius** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#120]
Like half an hour ago, connected from Spain.

**Comment by bbindreiter** [comment]
Can't confirm. Works here.

**Comment by obaldius** [comment]
Sorry, everything is back to normal.

**Comment by obaldius** [comment]
Ok so the on device activity is VERY inconsistent. It'll fail over a 50% of the times. It doesn't work or triggers too late. Is anybody else experiencing this issue?

**Comment by Varguit** [comment]
> Ok so the on device activity is VERY inconsistent. It'll fail over a 50% of the times. It doesn't work or triggers too late. Is anybody else experiencing this issue?

Same here, sometimes I get no response and sometimes the response arrives after 10 seconds or more.
Also from Spain.

**Comment by obaldius** [comment]
Ok, sorry again. It fucked me up for two or three days and apparently now it's working fine again.
