### ISSUE TITLE
Exception with error and stopping.

### ISSUE THREAD

**Issue by Mitchell-kw-Lee** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#122]
below error occured.

17 Apr 22:32:07 - [info] [alexa-remote-account:xxxxxxxxxx Account] intialising "xxxxxxx Account" with the PROXY method and saved data...
17 Apr 22:32:10 - [red] Uncaught Exception:
17 Apr 22:32:10 - [error] TypeError: response is not iterable
    at /config/node-red/node_modules/node-red-contrib-alexa-remote2-applestrudel/lib/alexa-remote-ext.js:495:26
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[22:32:10] INFO: Service Node-RED exited with code 1 (by signal 0)

**Comment by pebl-hank** [comment]
Looks a bit like https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/issues/113

**Comment by Mitchell-kw-Lee** [comment]
Well, with given message, 
there is no reason to decide that same. Seems different due to different crash line number.

**Comment by dajuly20** [comment]
I have something similar. :-/

/Apr 30 21:06:01 pihole Node-RED[18876]: 30 Apr 21:06:01 - [info] [alexa-remote-account:Julians Amazon account] intialising "Julians Amazon account" with the PROXY method and saved data...                                                   
Apr 30 21:06:01 pihole Node-RED[18876]: 30 Apr 21:06:01 - [red] Uncaught Exception:                                                                                                                                                           
Apr 30 21:06:01 pihole Node-RED[18876]: 30 Apr 21:06:01 - [error] Error: WebSocket was closed before the connection was established                                                                                                           
Apr 30 21:06:01 pihole Node-RED[18876]:     at WebSocket.close (/home/julian/.node-red/node_modules/ws/lib/websocket.js:285:14)                                                                                                               
Apr 30 21:06:01 pihole Node-RED[18876]:     at AlexaWsMqtt.disconnect (/home/julian/.node-red/node_modules/alexa-remote2/alexa-wsmqtt.js:844:28)                                                                                              
Apr 30 21:06:01 pihole Node-RED[18876]:     at AlexaRemoteExt.stop (/home/julian/.node-red/node_modules/alexa-remote2/alexa-remote.js:788:30)                                                                                                 
Apr 30 21:06:01 pihole Node-RED[18876]:     at AlexaRemoteExt.resetExt (/home/julian/.node-red/node_modules/node-red-contrib-alexa-remote2-applestrudel/lib/alexa-remote-ext.js:593:8)                                                        
Apr 30 21:06:01 pihole Node-RED[18876]:     at AlexaRemoteAccountNode.resetAlexa (/home/julian/.node-red/node_modules/node-red-contrib-alexa-remote2-applestrudel/nodes/alexa-remote-account.js:392:15)                                       
Apr 30 21:06:01 pihole Node-RED[18876]:     at AlexaRemoteAccountNode.initAlexa (/home/julian/.node-red/node_modules/node-red-contrib-alexa-remote2-applestrudel/nodes/alexa-remote-account.js:450:9)

**Comment by Mitchell-kw-Lee** [comment]
Well...
All you guys should go to the package 'node-red-contrib-alexa-remote2-mattl0'
which is most recent one.
I have changed earlier.

**Comment by bbindreiter** [comment]
I cannot reproduce it. Are you guys on pitangui.amazon.com ?

@Mitchell-kw-Lee the code on https://github.com/MattL0/node-red-contrib-alexa-remote2-mattl0 is identical.

**Comment by Mitchell-kw-Lee** [comment]
@bbindreiter Is it? But after change the package in Node red of HA to nattIO's, it disappeared. and never seeing so far (after the day it posted)
