### ISSUE TITLE
Alexa Event - Audioplayer State Change does not see playing in > 5.0.25

### ISSUE THREAD

**Issue by FlorianDessloch** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#125]
Since a while ago the "Alexa Event" node set to "Audioplayer State Change" does not see the event "PLAYING" and send it out in msg.payload.audioPlayerState any more.
INTERRUPTED and STOPPED are recognized and transmitted.

How to reproduce:
Set up a  "Alexa Event" node set to "Audioplayer State Change".
Connect a debug node set to complete msg to the output.
Tell Alexa to play a song, no event will be recognized.
Tell Alexa to stop.
An Event will trigger.

occures in version > 5.0.25
resetting to 5.0.25 solves the problem.

**Comment by dajuly20** [comment]
I think I have the same problem. 
I could confirm it with your repro steps, exactly the same behaviour.

**Comment by bbindreiter** [comment]
@FlorianDessloch which version did you rollback to to make it work again? Thanks for reporting

**Comment by FlorianDessloch** [comment]
@bbindreiter I rolled back to 5.05.25
that version comes with a downside, too.
I get errors at 4pm CET every day, but it does not restart nodered. it seems to reauthenticate an initialize.
