### ISSUE TITLE
On Device Activity not working

### ISSUE THREAD

**Issue by deexno** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#13]
So I have the following problem: 

I first used alexa-remote2 which worked great except for the "On Device Activity". So I uninstalled alexa-remote2 and removed all flows from nodered where this module was included and installed applestrudel (this project). But after I tried the "On Device Activity" there, I noticed that I still have the same problem and that I don't get any output from this trigger (no matter on which Echo I try to execute a voice command).

A few infos about this:
- Service Host: alexa.amazon.it
- Page: amazon.it
- Lang: it-IT
- remote2 has been properly uninstalled and node red has been restarted. 
- nodered is installed in Hass
- My account was initialised correctly and it also shows "listening".
- All other nodes work except this one
- When testing, I don't get anything from the trigger, even when I try to output the whole message using the debugging node.

I would also be open to workarounds if there is no other solution...

Thank you so far for the wonderful project!

**Comment by jasazick** [comment]
Same here - started yesterday. Other Alexa nodes seem to be working without issue. Can't get anything from the debug node b/c the listening node doesn't even pick anything up.

**Comment by St4tikk** [comment]
Same issue here.  I rebooted the box node-red is on after some maintenance and now on device activity is dead.

**Comment by Cjkeenan** [comment]
https://github.com/Apollon77/alexa-remote/issues/132#issue-1011417647 looks like it is a bigger issue than we thought.

**Comment by bbindreiter** [comment]
Thanks for the link @Cjkeenan

**Comment by quadhammer** [comment]
It's not just the Italian server either: pitangui.amazon.com, or the main Amazon US server has stopped reporting device activity too.

**Comment by czacherl** [comment]
For me, my homematic sensor events are functioning, only Alexa Events are not received any longer.
My Homematic node was changed with "Listen Address not found". It got replaced by localhost.
I can post a Alexa voice command, which makes Alexa speak. So that way, it still works.

**Comment by Cjkeenan** [comment]
Working for me again. Make sure you refresh your cookie and restart all of your flows.

**Comment by Matten-Matten** [comment]
Bei mir läuft es jetzt auch wieder.

**Comment by bbindreiter** [comment]
Thanks guys for the feedback. Closing the issue.

**Comment by Matten-Matten** [comment]
leider wird es bei meinem system schon wieder nicht mehr gepusht.

**Comment by bbindreiter** [comment]
Thanks, but all praise should go to @Apollon77. I'll close this issue 👍

**Comment by josue1988** [comment]
While upgrading the remote2-applestrudel, I lost the alexa.summary trigger and now I can't execute in nodered my routines running by switch with the invocation
