### ISSUE TITLE
Slow sending commands when using "Speak at Volume"

### ISSUE THREAD

**Issue by BassTeQ** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#132]
Hello,

If using the "Speak" option, the devices respond very quickly.
![image](https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/assets/32693997/2d8d3827-fc8e-4829-9104-11bc3817b6c3)

However when using "Speak At Volume", it's very slow, and can take up to 15 seconds before the devices respond, it just sits at sending.
![image](https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/assets/32693997/a55f073e-81c8-4fbe-a948-d34e838fddab)
![image](https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/assets/32693997/7d1710d3-81ef-461e-b57d-f8fced6dfe32)

Any ideas?

Thanks

**Comment by bbindreiter** [comment]
Same problem here at the moment. Although sending is quick, yet on one of my Echos the message is delayed by 5-10s

**Comment by BassTeQ** [comment]
bump

**Comment by datbilling** [comment]
Announcements are also often very delayed. Sometimes it's instant, most times it is in the 'sending' state which can be for up to a whole minute. 

Not much use for time sensitive notifications. Any idea what's causing that?
