### ISSUE TITLE
Auth: open alexa app does not give me a notification and previous version redirect is incorrect

### ISSUE THREAD

**Issue by weha** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#136]
I'm running node-red on docker so I set "this ip" to 0.0.0.0 so I could access it.
The site loads but when it opens my Alexa app, no notification.
I click "previous version" but that redirects to 0.0.0.0 instead of the ip address I'm accessing it with.
Can you please fix the redirect to not use a host or use the ip address it is currently accessed by?

thanks!

**Comment by weha** [comment]
Bump

**Comment by ThaMighty90** [comment]
Bump

**Comment by weha** [comment]
bump
