### ISSUE TITLE
404 when tryingto login account

### ISSUE THREAD

**Issue by feu77** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#137]
Hi,

I just went from cakebaked as it suddenly stopped working 2 weeks ago. I got an error when trying to login localhost:3456 I get a 404 error. I uninstalled the nodes and installed applestrudel but I get the same error when trying to initiate the account. I enter the credentials, get the verification SMS and then land on a 404 error page.

Any help is welcome!

**Comment by duramson** [comment]
same here

**Comment by bachph** [comment]
Same here!

**Comment by ThaMighty90** [comment]
Still happening can't authenticate

**Comment by tiko2302** [comment]
Same for me, also from Germany

**Comment by tiko2302** [comment]
As I found out in #143 I did not have 2FA activated and thus I always got the 404 message. After I activated 2FA and tried again I got the "successfully obtained cookie" message and the nodes said ready. So for me activating 2FA solved the issue
