### ISSUE TITLE
Issue with event node on device activity

### ISSUE THREAD

**Issue by Alulu2401** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#14]
Hi all,

I'm creating this issue because since 2 days i'm not able to use event node based on my device activity. 

I have a flow triggered by this node. For example when i'm saying "alexa, i'm leaving"  the flow starts and close all my shutter.
before 2 days i was able to see the payload from event node with description.summary and all needed stuff. 

Now... nothing there is no payload but the node is in listening state. 
i've checked my account, recreate the cookie even reinstalled applestrudel package nothing is working.

am i the only one with this ? 
thanks for your advise

**Comment by bbindreiter** [comment]
It's still working for me. I've setup some flows to create some activity during the next hours to see how reliable it is and whether it stops working at one point.

**Comment by bbindreiter** [comment]
Still working 👍

**Comment by saviothecnic** [comment]
I also installed node-red-contrib-alexa-remote2-applestrudel I see it works to hear commands but it doesn't work to send voice on my devices alexa accaunt alexa ita

**Comment by Levynger** [comment]
also suffering from this issue,
removed old node-red-contrib-alexa-remote2-v2 and installed applestrudel 5.0.7 
after proxy login, and after each deploy my flows, 
i have ""failed to load routines: "routines.map is not a function"" from the alexa account node

Device activity node doest recieve anything anymore - the rest are working fine.

**Comment by MrThiemann** [comment]
unfortunately I also have a problem with "device activity".
I'm using the latest version (5.0.7)

All other nodes of "applestrudel" work perfectly.
just just not listening to that.
<img width="521" alt="Bildschirmfoto 2021-12-30 um 09 04 19" src="https://user-images.githubusercontent.com/54147030/147733008-1edc525d-9dcd-483f-b4b6-2cc0490ebdc6.png">


Can i do anything?
