### ISSUE TITLE
Node red disconnected

### ISSUE THREAD

**Issue by GianZambo** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#148]
Randomly I have this error:

1 Oct 09:00:33 - [info] [alexa-remote-account:d6978b5bd1ab9c4f] intialising with the PROXY method and saved data...
1 Oct 09:08:31 - [red] Uncaught Exception:
1 Oct 09:08:31 - [error] Error [ERR_HTTP2_SESSION_ERROR]: Session closed with error code 6
    at new NodeError (node:internal/errors:405:5)
    at Http2Session.onGoawayData (node:internal/http2/core:689:21)

and node red disconnects.

I think it's about applestrudel palette but I am not sure ....

Do you have any ideas?

**Comment by niwre2019** [comment]
I had experienced the same problem and went back to an older version because of it. The problem has not occurred since, so it seems to be related to the current version.
