### ISSUE TITLE
Set up process on iOS (iPad) opens the Alexa app via port 3456?

### ISSUE THREAD

**Issue by nodecentral** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#154]
Hi

Following the set up instructions, when I go to the node red IP http://192.168.1.134:3456/ via the browser - it opens a page asking me to go to the IOS Alexa app ? Is that expected ?

![IMG_3720](https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/assets/4349292/e880f136-ecd7-4b35-8087-764a70f42b99)

**Comment by Matten-Matten** [comment]
Same issue
[#143](https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/issues/143)

**Comment by Matten-Matten** [comment]
Standardmäßig lauten die Einstellungen localhost, dies muss 127.0.0.1in Zukunft geändert werden.

**Comment by nodecentral** [comment]
Not sure that change will help me?

I read the other thread and I’m running node-red on docker under the host, so it doesn’t have its own IP, and entering either local host or 127.0.0.1 just gives me an error.. but when I access the :3456 port using the host IP which 192.168.1.134 (:1888 for node red, :3456 for this add-on) it always prompts me to opening of the Alexa app.

I assume this is due to how iOS handles calls to the redirected Amazon Alexa url, can you share the full url that’s supposed to be opened when I go to port 3456 ?

**Comment by nodecentral** [comment]
Not sure what happened but it worked, it gave me the Amazon Alexa log in and after I entered my credentials- it said 

 **Amazon Alexa Cookie successfully retrieved. You can close the browser**.

**Comment by nodecentral** [comment]
Nope, sadly I can get past the "Unexpected end of JSON input" error ☹️

It tells me I retrieved the cookie successfully each time after I have authenticated
Tried different browsers(chrome/safari on ios)
I’m in the UK, so it is set up for that

Would love to get this working …

**Comment by nodecentral** [comment]
Hi, still looking for any support anyone can give on this.. thanks

**Comment by Apollon77** [comment]
Please try with a PC or pad which is not opening the alexa app ... I think the login page from Amazon check if the app is there and directly uses this ... so you need a PC to login or such where the App is not on

**Comment by Spazpeker** [comment]
same problem for me, it is the same on the PC
It just opens the App on your Phone you get no alert
![image](https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/assets/27345433/52619955-0250-4331-bc97-222242aeedfa)

**Comment by Apollon77** [comment]
No this is a different issue!
You need to make sure that the IP/FQDN you really opern the proxy pahge in your browser is exect as the settin for "proxy own ip" - this match is used to detect the initial needed login start URL. So make sure to have the settings right!!

**Comment by Spazpeker** [comment]
> No this is a different issue! You need to make sure that the IP/FQDN you really opern the proxy pahge in your browser is exect as the settin for "proxy own ip" - this match is used to detect the initial needed login start URL. So make sure to have the settings right!!

I am putting in the local address ie 192.168.1.79:3456

**Comment by Apollon77** [comment]
And then you also need to call it with exaclty this IP and the port

**Comment by Spazpeker** [comment]
Ok it’s the local host on the account setting needs to be changed to the actual Ip Address.

done that and it’s back working 😀

**Comment by nodecentral** [comment]
> Please try with a PC or pad which is not opening the alexa app ... I think the login page from Amazon check if the app is there and directly uses this ... so you need a PC to login or such where the App is not on

Hi @Apollon77 

To confirm, it doesn’t take me to the app anymore, I’m taken to 192.168.1.22:3456 which is an Amazon Alexa login web page, where after I entered my credentials- it still says

**Amazon Alexa Cookie successfully retrieved. You can close the browser.**

But no matter how many times I go through this, when I go back to NodeRed the debug says "Unexpected end of JSON input"

☹️

**Comment by Apollon77** [comment]
this error (in the past) was mostly because of special stuff in the account or wrong parameters that do not match to the account country ... and in fact this issue is off topic for this thread :-) so open a new one with any infos
