### ISSUE TITLE
Reauthenticate every time I redeploy something?

### ISSUE THREAD

**Issue by tiko2302** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#155]
I do not know if this is a issue or normal behavior but I did not find any information regarding this.
I am authenticating my Alexa Account and every time I just change a little bit I have to re-authenticate my Amazon account.

This also robs me of the possibility to set the device that should speak to some flow variable as I can only set the device of a routine if I have an authenticated account but when I authenticated my account, set the device to flow.device and redeploy the account is not authenticated anymore and so on and so forth.

**Comment by hiagocosta** [comment]
i'm getting this too
anything that I change give error after

**Comment by tiko2302** [comment]
Thank you @fwedler after clicking a bit through I found the image @richsimpson postet under #163 to be very helpful. By changing the file path in my alexa account node everything seems to work for now.
