### ISSUE TITLE
Alexa - Other Node/Activities - Not responding - "Error: no JSON at handleR..."

### ISSUE THREAD

**Issue by richsimpson** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#156]
I have been using the other node/activities

![image](https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/assets/51749826/eaaa35fa-cbc1-4d18-bb44-335c6ba19033)

to listen to events (since the events node started playing up some months ago) and to identify the device called (to create a LAST ALEXA sensor), this was working well but now this node reports an error:

![image](https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/assets/51749826/8a22f025-c6df-4a9e-ac7b-2109366ff688)

"Error: no JSON at handleR..."

Other nodes are working, the routines and so on, so seems its an Amazon end problem, blocking something? Anyone else seeing this or even using this node?

The NodeRed AddOn log shows this:
![image](https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/assets/51749826/be13548d-89fe-4581-8715-0e17df94de1d)

Everythign up to date, no updates today though so seems to have just happened, hence assumption its an Amazon side issue.

**Comment by RDAppel** [comment]
@richsimpson Same thing here. Just started a few hours ago.

**Comment by MattL0** [comment]
Same

**Comment by richsimpson** [comment]
![image](https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/assets/51749826/4a267367-f065-4e17-82ee-0018d6d3d02d)

Encouraging that the /api/activities should be back open for business soon. Presume that will solve this

**Comment by DanPatten** [comment]
Here is the fix: https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/pull/157

**Comment by richsimpson** [comment]
Nice one @DanPatten Can I do anything to fix it or just wait for the code owner to update it and get the update from node red palette?

**Comment by sanjay900** [comment]
@richsimpson you can just throw `https://github.com/DanPatten/node-red-contrib-alexa-remote2-applestrudel/` in as your npm dependancy in node red, and that works. Probably would want to swap back once its merged in here though.

**Comment by bbindreiter** [comment]
I will merge it today. Nice work @DanPatten 

Thank you for contributing.

**Comment by bjesus75** [comment]
@sanjay900 can you tell me a step by step how to do that? i have HA OS with terminal. thks :)

**Comment by richsimpson** [comment]
Confirm the update solves the issue. 

Great work @DanPatten and @bbindreiter

**Comment by richsimpson** [comment]
> @sanjay900 can you tell me a step by step how to do that? i have HA OS with terminal. thks :)

Update solves it. Via manage palette 👍🏻 then restart node red.

**Comment by bjesus75** [comment]
yessssss thank youuuuu :) great work @DanPatten and @bbindreiter

**Comment by richsimpson** [comment]
Problem seems to be back although slightly different.
![image](https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/assets/51749826/3274e478-fdf9-485d-9b85-29d3aacf7392)

If I initialise I get one OK command, then this.

**Comment by sanjay900** [comment]
Odd, It still appears to be working fine for me at the moment
