### ISSUE TITLE
Error too many request

### ISSUE THREAD

**Issue by fabiosabariego** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#158]
Hello! I'm trying to actuate some devices in my Alexa (Sonoff device). I'm set to ON, then set to OFF, so far, everything Works Fine, but when I'm set to ON another time, i'm get an error "Too Many Request, try again in 5 minutes". Does anyone know how to solve this problem?

**Comment by bbindreiter** [comment]
It's a rate limitation. I think 2 requests for each device are allowed every 5m.

**Comment by fabiosabariego** [comment]
Is there any way to fix it? Or is it a limitation of Node-Red?

**Comment by bbindreiter** [comment]
It's a limitation of the Alexa API that they asked us to implement.
