### ISSUE TITLE
TypeError: Cannot read properties of undefined (Reading 'map')

### ISSUE THREAD

**Issue by jonferreira** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#160]
Greetings.

Today, out of the blue, my node-red instance got stuck in a crash loop. Upon investigating I've found out it was this node that was crashing node-red.

![image](https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/assets/7714292/3a0a9fa0-dd89-4e4e-84d1-e88748d364a5)

I've "fixed it" by changing:

`this.deviceByIdExt = new Map(response.devices.map(o => [o.serialNumber, o]));`

into

`this.deviceByIdExt = new Map(response.devices?.map(o => [o.serialNumber, o]));`

but someone smarter than me should take a look at it :D

**Comment by bbindreiter** [comment]
Hello, thanks for reporting. Could you make a PR with this null check please?

**Comment by jonferreira** [comment]
#161
