### ISSUE TITLE
Storage ALEXA.txt in config/node-red not longer possible

### ISSUE THREAD

**Issue by HaraldGithub** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#162]
With the last Node-Red-Update (16.0.2)

https://github.com/hassio-addons/addon-node-red/issues/1736#issuecomment-1812437543
https://github.com/hassio-addons/addon-node-red/issues/1740

it is not longer possible that node-red has access to the config-folder of HomeAssistant, so the re-autentification over
cockies in ALEXA.txt is not longer working.

Do you have a solution?

**Comment by richsimpson** [comment]
Have you seen this post? Same issue and solved mine
https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/issues/163

**Comment by HaraldGithub** [comment]
Thank you very much, it work’s for me too!!!

 

Von: richsimpson ***@***.***>
Antworten an: bbindreiter/node-red-contrib-alexa-remote2-applestrudel ***@***.***>
Datum: Sonntag, 19. November 2023 um 12:03
An: bbindreiter/node-red-contrib-alexa-remote2-applestrudel ***@***.***>
Cc: HaraldGithub ***@***.***>, Author ***@***.***>
Betreff: Re: [bbindreiter/node-red-contrib-alexa-remote2-applestrudel] Storage ALEXA.txt in config/node-red not longer possible (Issue #162)

 

Have you seen this post? Same issue and solved mine
#163
