### ISSUE TITLE
Verify Amazon account issue on port 3456 after update

### ISSUE THREAD

**Issue by AllStarzes** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#163]
Hi together,

i think after an update i saw in Node-Red this:
![image](https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/assets/91919099/a76b55fc-95b4-4105-8fe9-a18641a73868)

Okay, i open it in my Browser i see this one:
![image](https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/assets/91919099/2b5a2b78-de50-4fea-98cc-eab6f88f1b02)

After login with my credetentials i get this error:
![image](https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/assets/91919099/923d9946-450b-4114-86df-16d125d53629)

I changed nothing on my config, see here:
![image](https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/assets/91919099/9c22631b-39d3-49cf-ac7f-da4223f3af2b)

The only one i see my "amazon.txt" is missing. 

I try to verify alexa remote2 on my mobilephone, in inkognito tab, windows 10 and 11, firefox, chrome, edge. The redirect is busy.
I hope somebody can help me or have an idea where i can looking for.

---
NodeRed Version: v3.1.0
node-red-contrib-alexa-remote2-applestrudel: v5.0.46
Homeassistant Core: 2023.11.2
Homeassistant Supervisor: 2023.11.3
Homeassistnt Operating System: 11.1

**Comment by Maxbubbleb** [comment]
Hi, it's the same for me... I read that depend for a new default directory of the cache file. 
[](https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/issues/159#issuecomment-1815398774)

I hope someone makes a simple guide to solve the problem.

**Comment by Maxbubbleb** [comment]
I resolve the issue. 
In my case the cache file is not in the originally folder: /config/Alexa_Node-RED.cookie
but i found in this path:  /homeassistant/Alexa_Node-RED.cookie

I have change the file path in the nodered account and now working again!

**Comment by richsimpson** [comment]
yes seems change the current setup from config/node-red..... to homeassistant/node-red....

![image](https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/assets/51749826/cd6f9d38-2738-40c5-a9b4-92f2eec5b26f)

**Comment by AllStarzes** [comment]
Thanks a lot guys but my error is still there. I have changed the path and open the URL with Port 3456 and the error is the same. My **_amazon.txt_** file is missing after Update and if I want to create a new one with these HowTo -> [https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/blob/master/get_cookie.md](url) but if i open [alexa.amazon.com](url) you can´t login for lookin a cookie... Amazon has changed the way to app...

Or am I misunderstanding something? Sry :/

**Comment by richsimpson** [comment]
> Thanks a lot guys but my error is still there. I have changed the path and open the URL with Port 3456 and the error is the same. My **_amazon.txt_** file is missing after Update and if I want to create a new one with these HowTo -> [https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/blob/master/get_cookie.md](url) but if i open [alexa.amazon.com](url) you can´t login for lookin a cookie... Amazon has changed the way to app...
> 
> If I save my account information i see the error in NodeRed = "**Unexpected end of JSON input**"
> 
> Or am I misunderstanding something? Sry :/

my procedure to correct was:
update the file path for the location to create the file, in the Node Red node config. Inject something to that node to prompt the "open url...."
![image](https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/assets/51749826/d829eb5f-4336-470d-aec0-9fb963c3627b)

Open a browser and go that url. 
sign in with amazon password, then my 2FA code froom authenticator app
The new amazon.txt file was created and I can see it via my HASS file browser.
![image](https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/assets/51749826/4faa163f-70ca-42f0-84be-0cacaa9810e8)

My install is HASS supervised with the Node Red add on.

**Comment by AllStarzes** [comment]
THANKS GOD IS CHRISTMAS. Now i have the solution. @richsimpson, your guide was my inspiration of the soultion. I do you HowTo ste by step and it doesn´t work but the only thing in our configuration is: You use the 2FA in AMAZON. 

After i configuration the 2FA with authenticater APP ud save the Browser to login, you get now the reply of "cookie-success".

It works...

Now the summary: Change the Path like this from @richsimpson [https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/issues/163#issuecomment-1817705708](url) and configuration 2FA bevor authorize you amazon account .

Thanks a lot to all and I hope we can help other guys.

**Comment by quadhammer** [comment]
> yes seems change the current setup from config/node-red..... to homeassistant/node-red....

I also had to create a blank .txt file for it work again, after changing the path.
