### ISSUE TITLE
no csrf found

### ISSUE THREAD

**Issue by devwolti** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#164]
I tried authenticating the node (IP:3456). 
It worked in Firefox (with no response) and the node is displaying "no csrf found" and on Chrome (here with "...successful. You can close the browser"), but the same result.
Anything i am doing wrong here?

**Comment by wwwDESIGN-basti** [comment]
same issue.

**Comment by djcrawleravp** [comment]
same here!
