### ISSUE TITLE
How to get current volume?

### ISSUE THREAD

**Issue by Diddlik** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#167]
For my workflow I need the current volume so that I can restore it afterwards, so far I have not found a way to read it out...

**Comment by abstract-entity** [comment]
Did you try 'speak at volume' so you don't have to read previous volume to restore it maybe ? 

![image](https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/assets/1453538/454a62d6-4c2a-42a6-8d93-49a374b26620)

**Comment by Diddlik** [comment]
"speek at volume" does not work.
It continues to use the current volume. My guess is that the commands are fired too quickly one after the other and it is not being processed by API.
