### ISSUE TITLE
"Deprecated API warning: Calls to RED.util.evaluateJSONataExpression must include a callback. This will not be optional in Node-RED 4.0."

### ISSUE THREAD

**Issue by michaelfuncke** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#170]
"Deprecated API warning: Calls to RED.util.evaluateJSONataExpression must include a callback. This will not be optional in Node-RED 4.0. Please identify the node from the following stack and check for an update on npm. If none is available, please notify the node author."

node-red-contrib-alexa-remote2-applestrude v5.0.48

**Comment by jwende** [comment]
same message here ...

**Comment by adelaiglesia** [comment]
Same here!

6/1/2024, 14:25:13
msg : string[270]
"Deprecated API warning: Calls to RED.util.evaluateJSONataExpression must include a callback. This will not be optional in Node-RED 4.0. Please identify the node from the following stack and check for an update on npm. If none is available, please notify the node author."

6/1/2024, 14:25:13
msg : string[1010]
"Error↵    at evaluateJSONataExpression (/opt/node_modules/@node-red/util/lib/util.js:775:18)↵    at Object.evaluateNodeProperty (/opt/node_modules/@node-red/util/lib/util.js:673:18)↵    at evaluateNodeProperty (/config/node_modules/node-red-contrib-alexa-remote2-applestrudel/lib/common.js:165:26)↵    at nodeEvaluateProperties (/config/node_modules/node-red-contrib-alexa-remote2-applestrudel/lib/common.js:186:9)↵    at nodeEvaluateProperties (/config/node_modules/node-red-contrib-alexa-remote2-applestrudel/lib/common.js:181:17)↵    at nodeEvaluateProperties (/config/node_modules/node-red-contrib-alexa-remote2-applestrudel/lib/common.js:181:17)↵    at /config/node_modules/node-red-contrib-alexa-remote2-applestrudel/lib/common.js:175:25↵    at Array.map (<anonymous>)↵    at nodeEvaluateProperties (/config/node_modules/node-red-contrib-alexa-remote2-applestrudel/lib/common.js:175:14)↵    at nodeEvaluateProperties (/config/node_modules/node-red-contrib-alexa-remote2-applestrudel/lib/common...."

**Comment by michaelfuncke** [comment]
> removed error message by adding a switch node with jsonata in front of the the Alexa routine node ...

@jwende 
Can you elaborate on this? What do you mean by a "switch node with jsonata"? How did you configure the switch node and how the Alexa routine node? You wouldn't have a screenshot maybe?

My Alexa routine node is supposed to announce the JSONata (msg.payload) but always returns "Error: Calls to RED.util.evaluateJSONataExpression must include a callback." since updating to NodeRED 4.0
