### ISSUE TITLE
Need a inject node thats works with the Alexa Smarthome Action node?

### ISSUE THREAD

**Issue by Meanmike1337** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#171]
I can't seem to get a inject node to send info to Smarthome Node / Action for a temperature valve, or see the Error!
Can you make an examples?

	
![Udklip121](https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/assets/59618326/95a82311-1975-4531-93ac-d04128681d99)

![Udklip12](https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/assets/59618326/546b988f-d9d0-44c2-bb4a-629bca563a5f)

**Comment by xPudda** [comment]
I have something like this and works:

![image](https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/assets/24530984/d4d9f4ef-cc29-48c2-8aa5-511f539030f3)

The function defines the payload and send it to the smarthome action with option "Action" selected. 
The topic should be the device name into Alexa:

![image](https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/assets/24530984/17ec6ca4-759f-45c6-84cd-f28ad3b4c654)
