### ISSUE TITLE
After auth it throws me to a 404 page

### ISSUE THREAD

**Issue by douglasmauro** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#174]
After going through the auth on: http://192.168.123.70:3456

uname/pass and then putting in the code from my phone....it then throws me to a 404 page: 

http://192.168.123.70:3456/www.amazon.com/404

Going back to node-red it doesn't show auth'ed and wants to repeat steps.

Also: for filepath how can I confirm it has the correct permissions and correct?

**Comment by casistack** [comment]
For anyone having the issue i had the same and opened a browser session in incognito and that worked.

**Comment by Apollon77** [comment]
In fact the real solution is described here: https://github.com/Apollon77/alexa-remote/#issues-when-getting-the-cookie-and-tokens-initially
Such a 404 or other starnge errors during cookie process is caused by old OTP/2FA settings. Update them and all is fine

**Comment by douglasmauro** [comment]
clearing cookies and switching my amazon to 2FA works.  Issue I am having now is when I click deploy in node-red it wants me to re-auth the account again.  Expected?

BTW When I did the login/2fa on my computer I did CHECK the box that says don't require 2fa on this device (was this right?)

Thanks.

**Comment by Apollon77** [comment]
Check which "FA/OTP method is active for your account, if still SMS based then Update to the current one. Then it should work

**Comment by EdwinNe** [comment]
Thanks!
