### ISSUE TITLE
Error: getaddrinfo EAI_AGAIN bob-dispatch-prod-eu.amazon.com

### ISSUE THREAD

**Issue by GianZambo** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#176]
Hi,
it's not the first time this has happened ...
when my router loses internet connection my node-red crash and this is the error ...

[error] Error: getaddrinfo EAI_AGAIN bob-dispatch-prod-eu.amazon.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)

In node-red I have error handling but evidently is not sufficient, it's possible improve the error handling of the node applestrudel to avoid node-red crash?

**Comment by GianZambo** [comment]
It would be good manners reply to posts, even just to say that was written a bull.....
Given that this is my second post without answer I won't write anymore and I will cease my economic support to this project...

Regards

**Comment by gtnscebba** [comment]
@GianZambo, You are right, but very often you don't respond trivially because you haven't a correct answer, so better not to say anything.
You have to be patient and sooner or later someone will suggest a solution.

**Comment by bbindreiter** [comment]
It certainly is possible to improve the error handling. You may open a PR and I'll happily merge it. I think everyone would appreciate your contribution very much.

Regarding the "economic support". I have not received money from anyone and I certainly also don't intend to. 

Thanks for understanding that I simply do not have the time to do more at the moment.
