### ISSUE TITLE
Authentication Issue - Get stuck in QR Code Login

### ISSUE THREAD

**Issue by DerMalsy** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#177]
Hi,

since WEB UI of Alexa is not available anymore I get redirected to login by a QR Code using my Alex App. Following the URL in the QR code just forwards me to open this stupid Alexa App and then nothing happens. By that I do not get the Cookie to get my new NodeREd installation working again.
As IP I am using the real IP, But also tried localhost (for sure not works) and 127.0.0.1
As I have seen in other problems, the real IP should be fine?
Also activated 2FA now - no change.

What I am missing?
Thank you :)

BR Sven

**Comment by Koneisto** [comment]
Same issue here. The QR code only opens the App on the phone, nothing else. I'm running Node-Red in a container on a different machine and the phone is an iPhone.

**Comment by etofi** [comment]
I would also be interested to know how this works. I can only see the homepage and I have the app on my Android phone. How are you supposed to get a cookie?

**Comment by NeoDuder** [comment]
Same issue here.

**Comment by iyashwant** [comment]
Is there any work around for this?
