### ISSUE TITLE
Alexa Cookie request repeats continous

### ISSUE THREAD

**Issue by Martin-OHV** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#178]
Hi,

i Fading an issue since a while... 

if i use /home/pi/ as FilePath in the Config Node, i get an error:

"EISDIR: illegal operation on a directory, read"

If i let the Filepath blank, it works and i get asked to open the Authentication site. after logon i receive:

Amazon Alexa Cookie successfully retrieved. You can close the browser.

but the Initialize Node still shows up with "open ... in your browser"
![image](https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/assets/147791139/0c17e4db-8529-49c9-83d9-910054a731b0)

I already checked permissions on /home/pi/ and it is 0777 for user/group pi... 

Using NodeRed v2.2.2 on Raspberry PI with node-red-contrib-alexa-remote2-applestrudel v5.0.49

Any ideas?

**Comment by bbindreiter** [comment]
Put a path to an empty file, not a directory. Then it'll work.

Something like this:
![image](https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/assets/3252801/02d47948-fdf8-4b7f-bd96-b3aa0e381a27)

**Comment by Martin-OHV** [comment]
*facepalm* so sorry mate... Thank you. This fix the issue with the "EISDIR: illegal operation on a directory, read" error...

Unfortunatly i get this now:
"failed to load smarthome devices: "Timeout""
"failed to load smarthome devices: "Timeout""
"Initialisation was aborted!"

Source of all 3 is the config node. The Init Node says: "Init with Proxy" and the On Device Activity says "listening", but nothing happens.

i watching the whole Message Object of the Dev Activity Node with an Debug node and no commands from any Alexa device are sending

Thank you for you support
