### ISSUE TITLE
SSML audio tag

### ISSUE THREAD

**Issue by jibdata** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#18]
It seems that the SSML audio tag is not honoured in the Alexa Routine node.
I have tried this:
```
<speak>
    Testing
    <audio src="https://<some file path and file>.mp3" />
</speak>
```

I have also tried to play a file from AWS S3 bucket without any luck.

Only the text is spoken, and audiofile is not played.

https://developer.amazon.com/en-US/docs/alexa/custom-skills/speech-synthesis-markup-language-ssml-reference.html

**Comment by bbindreiter** [comment]
Yes, you're right, it doesn't work. See https://github.com/586837r/node-red-contrib-alexa-remote2/issues/17
