### ISSUE TITLE
On Device Activity not listening

### ISSUE THREAD

**Issue by IanIreland** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#182]
Node-Red v3.1.6, contrib-alexa-remote2-applestrudel 5.0.49 I am trying to trigger flows from Commands spoken to Alexa. I have the Alexa Event node set to Device Activity.  My Alexa account appears to be authorised using Proxy. If I use the Alexa Init to manually initialise, the On Device Activity briefly changes to Yellow and says Started Listening but after a couple of seconds changes to grey and says listening. However, it doesn't respond to any commands from Alexa, nothing shows in debug.
Any advice appreciated.

**Comment by iyashwant** [comment]
is this module still working? I'm unable to use proxy login, it takes me to a qr page

**Comment by jnpetersen** [comment]
I was having the same issue, I was looking around, and noticed that the `Events` and `Auto Query Activities` were blank.  When I put both of these to `On`, I was not seeing in my debug from the debug node off the Alexa Event node, the messages I was looking for.  Hope this helps.

**Comment by IanIreland** [comment]
That worked - thank you.
