### ISSUE TITLE
How to use in Japan?

### ISSUE THREAD

**Issue by huzisuke** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#23]
Thank you for developpers, this is awosome library.

When the people in Japan use this library, I consider we need to use below settings,
    Service Host: "alexa.amazon.co.jp"
    Page: "amazon.co.jp"
    Langage: "ja-JP".
But I can't get authentication with that settings.
The node says "Unexpected end of JSON input".
Please let me know how to use this node in Japan.

Some Japanese describes solutions, like modifing alexa-cookie.js and proxy.js,  however they are for past version.

**Comment by bbindreiter** [comment]
Good chances that it works now, please update to the latest version and retry:

More info:
https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/issues/53

**Comment by Apollon77** [comment]
Yes that would be very interssting! If it wouks that way greart ... if not I hve one more thing to try for you
