### ISSUE TITLE
Please explain "redeploy" v 5.0.7

### ISSUE THREAD

**Issue by bwims** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#24]
Hello,

the changelog for v 5.0.7 says "Redeploy all nodes after upgrade"

Sorry to appear dumb, but what does this mean exactly?  Something other than renewing the cookie?

Thanks

B.

**Comment by bbindreiter** [comment]
Hi, in Node-Red top right corner in the menu you can redeploy (that's basically a reload and reinit) flows/nodes.

**Comment by bwims** [comment]
Duh!  I'd complete disassociated your use of the word with the literal button and its "full" dropdown.

What a twit!

Many thanks indeed!

B.

**Comment by bbindreiter** [comment]
No worries, happy to help.
