### ISSUE TITLE
Frequent "NO JSON" error messages

### ISSUE THREAD

**Issue by alexruffell** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#30]
I frequently get NO JSON error messages on applestrudel nodes. The image below is an example. All this sequence does is to set the normal or quiet volume on 3 echoes I most often use. I added a 1s delay between them thinking the issue might be due to commands being issued too fast to multiple devices, but it clearly did not help in the example below:

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/4006944/143774957-c75818b3-2efe-4580-8eed-e0c11c7809ba.png">

`
[{"id":"a7a50df4d4bc87a6","type":"alexa-remote-routine","z":"b04104f328152109","name":"Volume - Living Room Echo","account":"8c670444753716f9","routineNode":{"type":"volume","payload":{"value":{"type":"msg","value":"volume"},"mode":{"type":"str","value":"set"},"devices":["G2A1A60304370EPE"]}},"x":800,"y":1040,"wires":[["4ad58710fe186a47"]]},{"id":"78d032dca92c38c1","type":"inject","z":"b04104f328152109","name":"Volume 60","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"true","payloadType":"bool","x":240,"y":1120,"wires":[["53c28be690b57176"]]},{"id":"71f9302072c83608","type":"inject","z":"b04104f328152109","name":"Volume 30","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"true","payloadType":"bool","x":240,"y":960,"wires":[["04d0aec8a67ffbf2"]]},{"id":"1924984cb0adea31","type":"server-state-changed","z":"b04104f328152109","name":"Quiet Mode","server":"6f1799ba.17e938","version":3,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"input_boolean.quiet_mode","entityidfiltertype":"exact","outputinitially":false,"state_type":"str","haltifstate":"on","halt_if_type":"str","halt_if_compare":"is","outputs":2,"output_only_on_state_change":true,"for":0,"forType":"num","forUnits":"minutes","ignorePrevStateNull":false,"ignorePrevStateUnknown":false,"ignorePrevStateUnavailable":false,"ignoreCurrentStateUnknown":false,"ignoreCurrentStateUnavailable":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"},{"property":"data","propertyType":"msg","value":"","valueType":"eventData"},{"property":"topic","propertyType":"msg","value":"","valueType":"triggerId"}],"x":230,"y":1040,"wires":[["04d0aec8a67ffbf2"],["53c28be690b57176"]]},{"id":"04d0aec8a67ffbf2","type":"change","z":"b04104f328152109","name":"Volume - Quiet","rules":[{"t":"set","p":"volume","pt":"msg","to":"30","tot":"num"}],"action":"","property":"","from":"","to":"","reg":false,"x":480,"y":1000,"wires":[["a7a50df4d4bc87a6"]]},{"id":"53c28be690b57176","type":"change","z":"b04104f328152109","name":"Volume - Normal","rules":[{"t":"set","p":"volume","pt":"msg","to":"60","tot":"num"}],"action":"","property":"","from":"","to":"","reg":false,"x":490,"y":1080,"wires":[["a7a50df4d4bc87a6"]]},{"id":"8c148d5be7686ceb","type":"comment","z":"b04104f328152109","name":"Change volume based on Quiet Mode","info":"","x":1030,"y":940,"wires":[]},{"id":"d837aad6881aa9ad","type":"alexa-remote-routine","z":"b04104f328152109","name":"Volume - Kitchen Echo Show","account":"8c670444753716f9","routineNode":{"type":"volume","payload":{"value":{"type":"msg","value":"volume"},"mode":{"type":"str","value":"set"},"devices":["G000RA07845712UK"]}},"x":1120,"y":1040,"wires":[["8bb46901796082cf"]]},{"id":"e1cc573daa45b089","type":"alexa-remote-routine","z":"b04104f328152109","name":"Volume - Master Bedroom Echo","account":"8c670444753716f9","routineNode":{"type":"volume","payload":{"value":{"type":"msg","value":"volume"},"mode":{"type":"str","value":"set"},"devices":["G090P308746204ET"]}},"x":1450,"y":1040,"wires":[[]]},{"id":"4ad58710fe186a47","type":"delay","z":"b04104f328152109","name":"","pauseType":"delay","timeout":"1","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"allowrate":false,"outputs":1,"x":960,"y":1120,"wires":[["d837aad6881aa9ad"]]},{"id":"8bb46901796082cf","type":"delay","z":"b04104f328152109","name":"","pauseType":"delay","timeout":"1","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"allowrate":false,"outputs":1,"x":1280,"y":1120,"wires":[["e1cc573daa45b089"]]},{"id":"6e0752c01f64da71","type":"comment","z":"b04104f328152109","name":"Delay = attempt to solve/reduce NO JSON error","info":"","x":1560,"y":1120,"wires":[]},{"id":"8c670444753716f9","type":"alexa-remote-account","name":"","authMethod":"proxy","proxyOwnIp":"192.168.1.41","proxyPort":"3456","cookieFile":"/config/node-red/amazon.txt","refreshInterval":"3","alexaServiceHost":"pitangui.amazon.com","amazonPage":"amazon.com","acceptLanguage":"en-US","onKeywordInLanguage":"","userAgent":"","useWsMqtt":"on","autoInit":"on"},{"id":"6f1799ba.17e938","type":"server","name":"Home Assistant","version":2,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true,"heartbeat":false,"heartbeatInterval":30}]
`

I can trigger the sequence many times and which one fails, if any, varies randomly. Usually one run and the error(s) clear but this morning I had to press the Inject 60 at least 5 or 6 times as I kept getting errors on the 2nd or 3rd echo node.

**Comment by bbindreiter** [comment]
Try, just for testing, 5s delay between the nodes. I believe it's a race condition

**Comment by TheNutHouse84** [comment]
Put your set volume nodes in parallel.

In my experience, when I use the set volume function the message payload is not passed through.

**Comment by alexruffell** [comment]
@bbindreiter I set the delay to 5s and while it may happen less frequently, I can easily cause the error by pressing the inject node while it is still working on the previous instance. It doesn't look right to me as the one that reports the failure is sometimes not even the one that is receiving the new update. In other words, the 1st echo got it's volume and the 1st delay is running. I press the inject button and the 2nd echo fails while the delay is still counting down.

<img width="815" alt="image" src="https://user-images.githubusercontent.com/4006944/144146305-5f283241-ff0b-4825-b46a-d397eab10560.png">

`[{"id":"a7a50df4d4bc87a6","type":"alexa-remote-routine","z":"b04104f328152109","name":"Volume - Living Room Echo","account":"8c670444753716f9","routineNode":{"type":"volume","payload":{"value":{"type":"msg","value":"volume"},"mode":{"type":"str","value":"set"},"devices":["G2A1A60304370EPE"]}},"x":820,"y":1040,"wires":[["4ad58710fe186a47"]]},{"id":"78d032dca92c38c1","type":"inject","z":"b04104f328152109","name":"Volume 60","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"true","payloadType":"bool","x":240,"y":1120,"wires":[["53c28be690b57176"]]},{"id":"71f9302072c83608","type":"inject","z":"b04104f328152109","name":"Volume 30","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"true","payloadType":"bool","x":240,"y":1000,"wires":[["04d0aec8a67ffbf2"]]},{"id":"1924984cb0adea31","type":"server-state-changed","z":"b04104f328152109","name":"Quiet Mode","server":"6f1799ba.17e938","version":3,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"input_boolean.quiet_mode","entityidfiltertype":"exact","outputinitially":false,"state_type":"str","haltifstate":"on","halt_if_type":"str","halt_if_compare":"is","outputs":2,"output_only_on_state_change":true,"for":0,"forType":"num","forUnits":"minutes","ignorePrevStateNull":false,"ignorePrevStateUnknown":false,"ignorePrevStateUnavailable":false,"ignoreCurrentStateUnknown":false,"ignoreCurrentStateUnavailable":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"},{"property":"data","propertyType":"msg","value":"","valueType":"eventData"},{"property":"topic","propertyType":"msg","value":"","valueType":"triggerId"}],"x":230,"y":1060,"wires":[["04d0aec8a67ffbf2"],["53c28be690b57176"]]},{"id":"04d0aec8a67ffbf2","type":"change","z":"b04104f328152109","name":"Volume - Quiet (30)","rules":[{"t":"set","p":"volume","pt":"msg","to":"30","tot":"num"}],"action":"","property":"","from":"","to":"","reg":false,"x":490,"y":1040,"wires":[["a7a50df4d4bc87a6"]]},{"id":"53c28be690b57176","type":"change","z":"b04104f328152109","name":"Volume - Normal (60)","rules":[{"t":"set","p":"volume","pt":"msg","to":"60","tot":"num"}],"action":"","property":"","from":"","to":"","reg":false,"x":500,"y":1100,"wires":[["a7a50df4d4bc87a6"]]},{"id":"8c148d5be7686ceb","type":"comment","z":"b04104f328152109","name":"Change volume based on Quiet Mode","info":"","x":310,"y":960,"wires":[]},{"id":"d837aad6881aa9ad","type":"alexa-remote-routine","z":"b04104f328152109","name":"Volume - Kitchen Echo Show","account":"8c670444753716f9","routineNode":{"type":"volume","payload":{"value":{"type":"msg","value":"volume"},"mode":{"type":"str","value":"set"},"devices":["G000RA07845712UK"]}},"x":820,"y":1120,"wires":[["ed9dfe072c9e6c14"]]},{"id":"e1cc573daa45b089","type":"alexa-remote-routine","z":"b04104f328152109","name":"Volume - Master Bedroom Echo","account":"8c670444753716f9","routineNode":{"type":"volume","payload":{"value":{"type":"msg","value":"volume"},"mode":{"type":"str","value":"set"},"devices":["G090P308746204ET"]}},"x":830,"y":1200,"wires":[[]]},{"id":"4ad58710fe186a47","type":"delay","z":"b04104f328152109","name":"","pauseType":"delay","timeout":"5","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"allowrate":false,"outputs":1,"x":1060,"y":1040,"wires":[["d837aad6881aa9ad"]]},{"id":"b5cdd03ebe02e5b8","type":"change","z":"b04104f328152109","name":"Volume - Normal (50)","rules":[{"t":"set","p":"volume","pt":"msg","to":"50","tot":"num"}],"action":"","property":"","from":"","to":"","reg":false,"x":500,"y":1200,"wires":[["e1cc573daa45b089"]]},{"id":"ed9dfe072c9e6c14","type":"delay","z":"b04104f328152109","name":"","pauseType":"delay","timeout":"5","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"allowrate":false,"outputs":1,"x":1060,"y":1120,"wires":[["b5cdd03ebe02e5b8"]]},{"id":"8c670444753716f9","type":"alexa-remote-account","name":"","authMethod":"proxy","proxyOwnIp":"192.168.1.41","proxyPort":"3456","cookieFile":"/config/node-red/amazon.txt","refreshInterval":"3","alexaServiceHost":"pitangui.amazon.com","amazonPage":"amazon.com","acceptLanguage":"en-US","onKeywordInLanguage":"","userAgent":"","useWsMqtt":"on","autoInit":"on"},{"id":"6f1799ba.17e938","type":"server","name":"Home Assistant","version":2,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true,"heartbeat":false,"heartbeatInterval":30}]`

**Comment by alexruffell** [comment]
@TheNutHouse84 Based on my observations with the debug node, `msg.volume` never fails to be passed along. Could be due to the fact I am not using `msg.payload` - no idea. It was in parallel at first but I wanted to trigger the volume change one at a time to see if it was a race condition. I could have left it in parallel and used increasing delays though.

**Comment by dafi87** [comment]
I'm seeing this issue too, sadly.

**Comment by jonferreira** [comment]
been fighting with this error for months and months, since the original node. I did add a delay node which seems to help but doesn't really seem to be a permanent solution.

any ideas?

**Comment by bbindreiter** [comment]
I can reproduce the problem as well when setting the volume. Will try to have a look asap

**Comment by jonferreira** [comment]
> I can reproduce the problem as well when setting the volume. Will try to have a look asap

I'm pretty sure it's somehow related with sending two messages within X seconds.

As a workaround, instead of using two routine nodes in sequence to set volume + music / TTS, I've started using a "serial" command and so far (2h so not exactly sure this fixes it) it seems to work!

**Comment by adelaiglesia** [comment]
Can reproduce the problem!

**Comment by VisualReversal** [comment]
I'm still having this issue. Anyone else?

**Comment by jonferreira** [comment]
I presume this means there's a fix now?

**Comment by alexruffell** [comment]
@jonferreira I have not seen the issue in a long time so I presume something changed, or maybe it is due to the small delays I added between operations on different echos. Are you still seeing the issue?

**Comment by VisualReversal** [comment]
I have to say I was getting them like crazy but two things sorted it out. First, I build in small delays before each request for echo to do something. The second thing I did was move my echos off my guest Wi-Fi and into my primary Wi-Fi. That has been an all around good thing for eliminating a variety of different problems I was having.
