### ISSUE TITLE
Open IP every time I deploy node-red

### ISSUE THREAD

**Issue by tempus2016** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#31]
Every time I press deploy, I get asked to open the IP and enter my login details on the alexa website.  Is this how it's supposed to work?

**Comment by bbindreiter** [comment]
No, use `Auth Method: Proxy` and a file to store the cookie after the first login. Something like this:

![image](https://user-images.githubusercontent.com/3252801/145252430-e1028429-839b-4763-87fc-5572136acbca.png)
