### ISSUE TITLE
 data in flow. and global. is not persistent

### ISSUE THREAD

**Issue by stueng** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#34]
When using a routine node (might affect other nodes but not tested) if "devices" is set to flow.lastdeviceused (where flow.lastdevice is the serial numer) for example it works, but but does not save. As soon as you open the node the data which was previously entered into the devices field disappears. The flow will work and it will speak out of the correct alexa device, but only for a limited time, I assume until node red is restarted, or until the node is opened and closed again with the data now missing.

**Comment by zeldalegends** [comment]
Partial workaround is to set Device in the configuration to something like msg.lastdevice and let the node be preceeded by a change node which set msg.lastdevice to flow.lastdevice. In this case an error message is produced saying there is a problem with the Alexa account, when you deploy the flows. But in my experience, it is a "false positive". The bug still persists, in any case.
