### ISSUE TITLE
Listening on device activity doesn't work

### ISSUE THREAD

**Issue by MrThiemann** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#36]
unfortunately I also have a problem with "device activity".
I'm using the latest version (5.0.7)

All other nodes of "applestrudel" work perfectly.
just just not listening to that.

<img width="521" alt="Bildschirmfoto 2021-12-30 um 09 04 19" src="https://user-images.githubusercontent.com/54147030/147743858-3a226922-e18d-4b00-a495-c090714d388c.png">

Can i do anything?

- - - - - - -
what I notice is that I have a message in the debug for the node. Does that have anything to do with it?

<img width="819" alt="Bildschirmfoto 2021-12-30 um 09 05 55" src="https://user-images.githubusercontent.com/54147030/147743878-38bb1eec-8a95-4279-a5e7-52bf18c0d75f.png">

**Comment by bbindreiter** [comment]
Ok 2 questions:

1. Has it ever worked for you or never? Because some folks are reporting that it works and then doesn't from time to time.
2. I presume you have routines setup. Are they showing up in the routine node dropdown like shown here:
![image](https://user-images.githubusercontent.com/3252801/147790541-1cdc9183-c8c6-4a1c-b522-192f7c204c6b.png)

**Comment by MrThiemann** [comment]
1.) Hey, thanks for your answer!
Yes, I am very sure that it has worked before.
i hadn't used it zawr before, but i remember a "positive debug message".

2.) I've set up routines, yes! everything works fine!

I have no idea why this doesn't work ...!?

**Comment by pshellguruwannabe** [comment]
Had same issue.  I created a new Alexa account with a new file requiring me to sign in again, and it started working.

**Comment by LuAusDu** [comment]
I had the same problem.
After Updating Node Red to the current Version, it worked again.

**Comment by MrThiemann** [comment]
unfortunately I still have the error. the only one where "listen on device" triggers when i let alexa say something for example...

but if I say, for example: alexa, what time is it.... then the node does not listen here. but that's actually exactly what I need.
because alexa is supposed to be in several rooms and i just want to say: alexa, turn on the light. and then the light should go on in the respective room

**Comment by matteo-bottero** [comment]
same issue for me: device activities still "freezed"  in listening state and I don't get any message  if i connect it to a debug node.
Palette version is 5.08 i'm using :Node-RED v2.1.6 as "addon"  (Current version: 10.3.4) inside Home Assistant 2021.12.10

Others nodes are working fine (call routin, speak chang evolume etc)

**Comment by sdholden28** [comment]
Similar issue for me, but it is intermittent. Sometimes On Device Activity fires and the flow completes, and sometimes it doesn't. When On Device Activity doesn't fire, there is no output at all. Its as if no one spoke to an Alexa device, when in fact they did. It appears to be random and I have not been able to isolate it despite extensive testing. I am running 5.09

**Comment by dajuly20** [comment]
I also start having those problems :-( 
It seems like the node doen't trigger anymore at all... no "on device activity" no "on music player state change".

Are there any breaking changes from the dependencies?

**Comment by dajuly20** [comment]
I tried it now on a total fresh node-red intall on my local mashine.

![image](https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/assets/7774238/c313d0d5-4157-4941-af01-4e6b47be9725)

![image](https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/assets/7774238/1f34f4ee-3cc0-4fdb-934e-c736c56bbdcb)

![image](https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/assets/7774238/5abcdd17-4477-460a-a3c1-687aabffe7a6)

![image](https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/assets/7774238/3d261778-7724-4bef-9201-7e43648ad69b)

When I say something I can see console output... but nothing is triggered & nothing happens :-(

**Comment by bbindreiter** [comment]
Yes, it's broken again, let's continue here -> https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/issues/130
