### ISSUE TITLE
No csrf found

### ISSUE THREAD

**Issue by Tinchen9b** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#38]
![2022-01-04_14-56-06](https://user-images.githubusercontent.com/96677394/148070285-9908fe4b-1bff-48ae-b5ae-ac8d839924c4.jpg)
Hello, 

i have just installed the this node, configured the node as in this blog
https://tech.scargill.net/node-red-contrib-alexa-cakebaked/
and I get the error "No csrf found"

Any ideas what I am doing wrong?

**Comment by ikarisan** [comment]
Did you restart node-red?
