### ISSUE TITLE
Howto get a spoken command to the output

### ISSUE THREAD

**Issue by mssib281** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#41]
Hello all together,

I'm new to Node-Red.
I checked and tested already all examples.
I would like to use a to the alexa spoken command, for example "switch plug1 on".
Can anybody help, 
- which Node I have to use?
- which values ahve to be used in the fields?

Thank you very much in advance

**Comment by zyankali333** [comment]
Routine Node -> "Text Command" -> Choose your Command and your Device

**Comment by mssib281** [comment]
Hi @zyankali333 ,

thank you for your fast response.
I didn't get it working. Maybe I described not in the correct way.
So I made a testflow. 
In this flow I use, instead of the Alexacommand, two inject-nodes.
On inject-node switches on a plug, the other switches off the plug. This works so far.
Now is my idea to replace the inject-nodes by alexa-nodes, so that when I say to alexa "switch on the plug" the plug will be switched on and the same with switch off.

I've attached the testflow.
After download please rename Alexa_testflow_plug1.json.txt to Alexa_testflow_plug1.json.
[Alexa_testflow_plug1.json.txt](https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/files/7841936/Alexa_testflow_plug1.json.txt)

**Comment by bbindreiter** [comment]
If the plug is connected to Alexa via a skill it's going to be tricky. You could use the Event Node with type `Device Activity` and then create a command for the other plug and vice versa.

If the plugs are connected via Node-Red (e.g. by using `node-red-contrib-amazon-echo`) it's fairly easy.
