### ISSUE TITLE
Alexa Echo node doesn't allow flow or global vars

### ISSUE THREAD

**Issue by smcgann99** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#43]
If I change the device to be a flow.var it just reverts back to the first device in the list ?

![image](https://user-images.githubusercontent.com/52132596/149634334-d4026b58-58ba-41eb-aa76-68050488c9ef.png)

**Comment by zeldalegends** [comment]
Maybe it is connected to bug: https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/issues/34

**Comment by smcgann99** [comment]
Yes this sounds like the same issue as [#34](https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/issues/34)
