### ISSUE TITLE
Alexa tells me there are no devices

### ISSUE THREAD

**Issue by jojora18** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#47]
Hey, 
maybe you can help me with this problem.

When I tell Alexa to for example switch on the TV, the TV get switched on.... So applestrudel works, but Alexa tells me there are no smart home devices calld "TV" connected. 
Is there a skill or any other way to give Alexa some "dummy devices" she can search for.

Thanks for any help.
---jo--

**Comment by bbindreiter** [comment]
Please tell us what you want to achieve. What I personally use is `node-red-contrib-amazon-echo`. You can add devices by creating a hub, that are found by Alexa. Those are fake Philips Light Bulbs and you have basic commands like on/off and can even play around with the brightness (integer value from 0-100).
