### ISSUE TITLE
Account cannot be initialized: Timeout

### ISSUE THREAD

**Issue by ikarisan** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#48]
After upgrading from the old "node-red-contrib-alexa-remote2" to "node-red-contrib-alexa-remote2-applestrudel" I cannot initialize my account. :( 

These are the messages I can see: 

21 Jan 19:35:01 - [info] [alexa-remote-account:ALEXA] intialising "ALEXA" with the COOKIE method and saved data...
21 Jan 19:35:01 - [warn] [alexa-remote-account:ALEXA] open 10.10.0.42:3456 in your browser
21 Jan 19:36:07 - [warn] [alexa-remote-account:ALEXA] failed to load music providers: "Timeout"
21 Jan 19:36:07 - [warn] [alexa-remote-account:ALEXA] failed to load smarthome devices: "Timeout"
21 Jan 19:36:17 - [error] [alexa-remote-init:982d621f5d989e80] Timeout

I tried both, "proxy" and "cookie" as authentication mode.

**Comment by ikarisan** [comment]
At the moment I am using the (randomly chosen) "node-red-contrib-alexa-remote2-mattl0" (4.1.1) fork and it works. @bbindreiter du you need any further logs/information?

**Comment by Cjkeenan** [comment]
I am running into this issue in the last day as well.
