### ISSUE TITLE
On device activity not working

### ISSUE THREAD

**Issue by obaldius** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#49]
it's stopped working today. Is anybody else suffering this issue?

**Comment by furious1y** [comment]
It's never worked for me, I'm on 5.0.8.
I'm hoping this isn't going to be a cursed node, where it's perpetually forked as one dev after another stops bothering with it after working on it for a few months.

**Comment by obaldius** [comment]
it came to working a few hours later. thanks

**Comment by bbindreiter** [comment]
For some there are outages all the time. For me personally it always works. Just checked my logs, and there's plenty of activity throughout the day. 

I think it's some websocket connection that is dropped (unnoticed), however unfortunately I don't have time to actively debug this at the moment.
