### ISSUE TITLE
Custom command and answer

### ISSUE THREAD

**Issue by elyonardo** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#57]
Hi all!
I'm trying to use "On Device Activity" node to give a custom command to Alexa turning on light and setting the color.
It works, but Alexa answers that it doesn't recognize the command or something similar (but turn on light and set color correctly).

Is there a workaround to avoid Alexa's answers?

**Comment by bbindreiter** [comment]
I've tried the same. I don't know any workarounds except creating routines that do nothing. Would be glad if someone could share something.

**Comment by elyonardo** [comment]
Great! So I have to try to make a void routine with an invocation name that node red recognize to do something?

**Comment by bbindreiter** [comment]
It depends on what you want to achieve.

There's functionality to emulate devices. Then you get all of this out of the box. Alexa finds those devices and thinks they're lightbulbs. 

https://flows.nodered.org/node/node-red-contrib-amazon-echo

**Comment by elyonardo** [comment]
My idea was to perform some actions by telling Alexa to "do something".
I tried with your suggestion and it might be a good solution.
But do you know if I can have a conversation with Alexa or other nodes with apple strudel or other nodes? For example, I activated the feature by saying "Alexa, talk to me", Alexa responds by saying "Hi! What's your name?" and she waits for my name and so on.

**Comment by superslaper567** [comment]
I alleviated this issue by making a routine in the alexa app, making the trigger phrase the same as the node red trigger phase, and then leaving the rest of the routine blank.
