### ISSUE TITLE
Not loading devices

### ISSUE THREAD

**Issue by jrens** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#6]
Happens for me on the entire fork hierarchy as of a few days ago, but it is no longer able to load smarthome devices. Get these in the logs

> [alexa-remote-account:3ec6e0d4.0f76d] failed to load routines: "routines.map is not a function"
[alexa-remote-account:3ec6e0d4.0f76d] failed to load music providers: "Timeout"
[alexa-remote-account:3ec6e0d4.0f76d] failed to load smarthome devices: "Timeout"

Followed by this whenever something tries to interact with previously configured devices

> smarthome entity not found:

![image](https://user-images.githubusercontent.com/11200400/128276509-df498469-34af-444d-a737-267bdd70dd22.png)

**Comment by jrens** [comment]
Timeout is caused lib/alexa-remote-ext.js line 219:

> this.getSmarthomeGroupsPromise().then(response => response.applianceGroups)

Commenting that out worked to fix my issue, though obviously groups are no longer appearing.

**Comment by bbindreiter** [comment]
I'm pretty sure that the underlying API has been changed. `applestrudel` is calling this function from `alexa-remote2`: https://github.com/Apollon77/alexa-remote/blob/20502e224ef8e4f7a78fcef96ca1df0a14886bb5/alexa-remote.js#L2147

**Comment by jrens** [comment]
Yes just tried. Uncommenting that line results in it failing.

**Comment by bbindreiter** [comment]
As your log shows above there's more than one call failing: routines, music providers and devices. I think there's something weird going on. After you've commented `getSmarthomeGroupsPromise`, do you still see the music providers timeout? Without seeing the exact responses from the Amazon API we're clueless.
