### ISSUE TITLE
Cookie recieved, but file not updated

### ISSUE THREAD

**Issue by Jmilesy** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#60]
Hi all,

I have the following set up:
![image](https://user-images.githubusercontent.com/34949583/164972069-f3332153-8e6e-4ebd-b155-00eefcd4116e.png)

I am able to access the webpage to get the cookie:
Amazon Alexa Cookie successfully retrieved. You can close the browser.

but it does not update the file.

I have checked that nodered can access the file by using a write file node and this works fine.

any ideas what i may be missing?

**Comment by bbindreiter** [comment]
Please create the file manually with the necessary write permission for node-red. Leave it empty, save it and retry please.

**Comment by Jmilesy** [comment]
Hi, sorry I have done that with cmod777 that was also the file I tested with the write to file

**Comment by jerome6994** [comment]
Good evening
I have the same problem with cookies.
I am under docker with this stack

I created the folder with `mkdir /appdata/nodered_test/data/cookie` and I also created the `cookie.txt` file

at the permissions level I put `chmod 0777 /appdata/nodered_test/data/cookie/cookie.txt` and `chmod 0777 /appdata/nodered_test/data/cookie`

but as soon as I restart node red you have to redo the cookie !
is there a particular handling under docker?

@Jmilesy did you manage to do it?

I deleted the IP for the screen
![image](https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/assets/66921143/3031cb9b-7bfa-43db-8b20-8b03ff687109)

Thank you for your help
