### ISSUE TITLE
How to construct a custom command using a text command as an option?

### ISSUE THREAD

**Issue by bwims** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#64]
Hello,

as "Text Command" appeared later than the documentation on "Custom Command", the relevant keywords are not documented.

I would like to construct a conditional custom command that creates a command dependent on parameters, and I would like "text command" to be one of those options.

What is the missing documentation please?

My guess would be -

{type: 'text',payload: { command: 'what time is it? }}

But I have no idea if those are the correct keywords, or if indeed they exist for the custom command.

Any assistance greatly appreciated!

B.

**Comment by Programie** [comment]
I'm also interested in sending a text command using the "Custom" option.

Checking the [code of the routine node](https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/blob/master/nodes/alexa-remote-routine.js#L294-L306) gives some hints to use the following object:
```json
{
    "type": "textCommand",
    "payload": {
        "text": "what time is it?",
        "device": "My Echo"
    }
}
```

But I didn't tested it yet.
