### ISSUE TITLE
Alexa-Remote2 has been updated.  Will this affect applestrudel?

### ISSUE THREAD

**Issue by bwims** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#68]
Please excuse my lack of expertise, but I saw [this ](https://github.com/Apollon77/alexa-remote/releases/tag/v5.0.0) today - does it imply a new version of Applestrudel?

**Comment by bbindreiter** [comment]
Yes, I'll wait a few days to see if some errors pop up and then release a new version.

**Comment by bwims** [comment]
Good move!  There has been an update every day for 4 days!  I wonder what new terrors Amazon have unleashed?

**Comment by bbindreiter** [comment]
Not seeing any breaking changes so far. My setup still works.

**Comment by bwims** [comment]
What about in 5.0 ? 

`BREAKING: SequenceNode methods throws an error on invalid data instead calling callback with error as before!`

**Comment by bbindreiter** [comment]
That's something that breaks the integration of the lib. I just have to change a bit of code. No problem ☺️

**Comment by bbindreiter** [comment]
https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/releases/tag/5.0.10

For me everything seems to work, but that was a 15 minute testing session only .. Please report back.

**Comment by bwims** [comment]
Uh-oh. Release v5.4.0 just came out.

When's he going to finish???
