### ISSUE TITLE
Listening on device activity stopped working

### ISSUE THREAD

**Issue by Vats-shop** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#69]
The listening on device function has been working great for a while now.  The last time it worked was yesterday early in the morning.  I performed lots of testing the day (7/2/2022) before without issue as I was working on a project. 

Nothing has changed system wise. All other functions appear to work just fine. I have restarted Node-Red, etc and still experience the issue.

**Comment by obaldius** [comment]
Did you get this figured out?

**Comment by Vats-shop** [comment]
> Did you get this figured out?

Unfortunately, no. I’m open to suggestions.

Everything else seems to work perfectly. I’m using the most up-to-date Version of node JS and Applestrudel.
