### ISSUE TITLE
"JSON Error" (like issue #53)

### ISSUE THREAD

**Issue by bdydrp** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#72]
Following on from issue #53 i get this everytime for an australian amazon account
Is there anything i can do/provide to help assist troubleshooting to get this node working in Australia??

Setup:
![image](https://user-images.githubusercontent.com/63593828/180593832-02e5a178-ea5a-49e2-9aea-319930cfb725.png)
Saving cookie to global variable

Cheers

**Comment by Apollon77** [comment]
I would consoder this a duplicate of #53 ... 

Please support in https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/issues/53#issuecomment-1194273167

**Comment by bdydrp** [comment]
Working with Apollon77 in issue #53 to resolve
