### ISSUE TITLE
failed to load routines: "routines.map is not a function"

### ISSUE THREAD

**Issue by bdydrp** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#74]
Anyone else get this error message randomly?
It started about a week ago for me
![Screenshot_20220903-190750_Samsung Internet](https://user-images.githubusercontent.com/63593828/188264694-0c2b51aa-1b4f-4f68-808c-96a53cb5f9ad.jpg)

**Comment by bdydrp** [comment]
> This is a really old issue. Doesn't seem to have any impact on functionality.. If it annoys you go to the alexa app and create a routine and the error will go away.

Thanks. Yes, correct. No impact on functionality, just keep seeing it in debug bar and reported it
Will try a routine and clear it
Cheers

**Comment by jackie-t** [comment]
Sure, I could create a routine, but that's a workaround. Would it hurt to simply check the routine object for the map function, before invoking it?

It's one line. 

`if (routine.map !== undefined) `
