### ISSUE TITLE
Ask node red status (read data from node red)

### ISSUE THREAD

**Issue by Cm-8** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#75]
Hi everyone,

Is it possible to read the values present on the node red?

I have a DHT11 (temperature and humidity sensor), on my P0 raspb with node red.
I need to ask Alexa:

-  what are the temperature and humidity of my room, or
-  know if a switch is ON or OFF.

Thanks

**Comment by turbo2ltr** [comment]
Check out https://flows.nodered.org/node/node-red-contrib-virtual-smart-home
You can create a virtual smart thermostat and keep it updated with your DHT11.
You can create a virtual smart switch and do the same with the switch.
This assumes you already have a way to read the sensor/switch into Node Red
There may be better ways but I use this way to read and control my really old wifi thermostat through alexa.
