### ISSUE TITLE
event node unexpected delay

### ISSUE THREAD

**Issue by brunialti** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#76]
I'm using an event node to get STT messages from all my connected Echos.
 When I say to Alexa "alexa, accendi lampada" it takes less than 1 second to send the message.
If I say "alexa, spegni lampada" it takes about 10 seconds.
I cannot image the reason why...

**Comment by Gml10** [comment]
I have the same problem, it happens sporadically. It is mainly observable in speech nodes. But I've seen it happen in other nodes. When it sends a command to the node it has a "pending" status.

**Comment by Gml10** [comment]
> I'm using an event node to get STT messages from all my connected Echos. When I say to Alexa "alexa, accendi lampada" it takes less than 1 second to send the message. If I say "alexa, spegni lampada" it takes about 10 seconds. I cannot image the reason why...


Did you manage to solve the problem? I still have a delay on practically all nodes, it happens 25% of the time I make a request.

**Comment by brunialti** [comment]
No I did'nt, unfortunately. It occours occasionally.
