### ISSUE TITLE
"no body" in Log

### ISSUE THREAD

**Issue by Matten-Matten** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#77]
Hallo, immer wieder bekomme ich bei den Nodes "no body" im Log ausgeworfen

![no body](https://user-images.githubusercontent.com/32074970/188936676-fda7aeb0-ba3d-4f1d-98d5-3928c74f2831.png)

Gruß
Matten Matten

**Comment by mdte123** [comment]
Am also seeing this (in the UK). 'strudel 5.0.20. Also from the Player Info node.

**Comment by Matten-Matten** [comment]
Gibt es bei den anderen Platformen wie ioBroker keine probleme beim Auslesen der Player State werte?

**Comment by bbindreiter** [comment]
Hi! Thanks for reporting. According to https://github.com/Apollon77/ioBroker.alexa2/issues/942#issuecomment-1245518119 it could be working again. I've updated to the latest lib, just in case, and published 5.0.21. Would you be so kind and retry?

If it doesn't work, I'll check out the workaround he implemented in iobroker.

**Comment by Matten-Matten** [comment]
hab es geupdatet wenn ich jetzt initialisiere steht
bei deviceAppName: "ioBroker Alexa2"
