### ISSUE TITLE
Account initialisation needed every couple of days

### ISSUE THREAD

**Issue by Mikee1234K** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#79]
I used to run applestrudel 5.02 on Node Red 3.x (not sure what version it was) on Docker. I use the init node which I injected every 2 hours, which kept my account initialised prefectly. I updated my Node Red to 4.0, and the init node stopped working. I updated to applestrudel 5.0.21, same thing. When the account is initialised (localhost:3456) it works fine. As soon as I trigger the init node, it shows please initialize localhost:3456. So I had to stop the automatic injection for the init node. Now, every couple of days I have to re initialize my account. Any ideas please ?

**Comment by Mikee1234K** [comment]
I think I might have found the issue. Somehow my amazon account settings have reverted to US authorisation settings from the UK with one of the updates. Having set it back to the UK, it seems to work again.

**Comment by SgtErnestBilko** [comment]
Did you solve this problem?  I have the same problem, but I've checked my authorisation settings and they are correct.
