### ISSUE TITLE
Device limit reached 

### ISSUE THREAD

**Issue by reddddich** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#80]
![image](https://user-images.githubusercontent.com/94436638/192627680-6e1084de-6304-4d5f-9489-f5560048c074.png)
Since a few days I get this message in node red. Any idea? Couldn´t find any option regarding device limitation.

**Comment by Gml10** [comment]
This is not from alexa-remote2 it is the node-red-contrib-virtual-smart-home package from the smart home virtual skill. This skill started to be paid for more than 7 registered/created devices, it is about 1.5 euros per month. Update your node-red-contrib-virtual-smart-home package.

**Comment by Gml10** [comment]
> ![image](https://user-images.githubusercontent.com/94436638/192627680-6e1084de-6304-4d5f-9489-f5560048c074.png) Since a few days I get this message in node red. Any idea? Couldn´t find any option regarding device limitation.

This is not from alexa-remote2 it is the node-red-contrib-virtual-smart-home package from the smart home virtual skill. This skill started to be paid for more than 7 registered/created devices, it is about 1.5 euros per month. Update your node-red-contrib-virtual-smart-home package.

**Comment by reddddich** [comment]
Thank you dude! I was definetly on the wrong way...
