### ISSUE TITLE
Not possible to open the authentification site

### ISSUE THREAD

**Issue by oehm2007** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#87]
Hey guys,
I am just trying to get the plugin working on my node red, but I am alredy struggling to log in my amazon acount for authentification. 
![image](https://user-images.githubusercontent.com/32645023/196453069-10cbbebd-8f4b-472b-aba0-fa1c8d53429b.png)
![image](https://user-images.githubusercontent.com/32645023/196453394-8fbfa02a-1b4a-40cb-94ac-24e06db99770.png)
![image](https://user-images.githubusercontent.com/32645023/196454499-679886f9-6ef5-41dd-9f18-c691ee9fc8f3.png)

My setup should be all right, but I cannot see any reason for not seeing the login Screen from amazon.

![image](https://user-images.githubusercontent.com/32645023/196455243-5a4f243d-613e-4a8e-bb96-f17a2bbb3c73.png)

Maybe someone could give me a hint, what I am doing wrong. I really appreciate your help.

**Comment by technowizard79** [comment]
Possible that port is in use already, or your firewall, etc., are blocking or forwarding it.  Try temporarily disabling those things and/or a setting up the account with a different port # like 8675 or 3090.

**Comment by oehm2007** [comment]
@technowizard79 : Thanks very much for your help. The reason for that issue was the port, which was not set as allowed in my homematic enviroment.
