### ISSUE TITLE
Speak stopped working

### ISSUE THREAD

**Issue by technowizard79** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#88]
Anyone else have "Speak" and "Speak At Volume" stop working on them tonight?  Everything else I normally use seems to work fine, such as execute routines (speech in those work fine), change volume, and even announce works fine.  Been using this node addon since 586837r was maintaining it, and I'm on the most current version of Applestrudel's (v5.0.21 as of writing).  Tried everything I could think of tonight... refreshing cookie, fresh authentication, restarting Node Red, new Alexa Node Account w/ new port #, power cycling echo devices, and finally deleting out all flows and removing/re-installing alexa-remote2-applestrudel (with and without flow backups)... sadly nothing fixed it.  I am on an older version of Node Red / Home Assistant, but I wouldn't think that's the issue.  I'll try updating temporarily (new versions break some things I need) to see if that resolves it, and will report back here if it does.

Of course it's not beyond Amazon to make change to things, so this may need an Apollon77 update, followed by Applestrudel updating his node, which we super appreciate btw!  Hopefully for everyone else it's just me, and something simple I'm not thinking of.

**Comment by bbindreiter** [comment]
I have just tried it manually and it worked. However, I could swear it didn't tell me the time earlier today. Also the Activity Log in the Alexa App stopped working a couple of hours ago and the manual test I just did doesn't show up either. So it's likely that there was some sort of outage.

**Comment by bbindreiter** [comment]
Alright, doesn't work anymore. Just failed again.

Fun fact, Announcement still works for me. You can switch to that as a workaround for now.
<img width="393" alt="image" src="https://user-images.githubusercontent.com/3252801/196661668-bf9b26f3-3bf9-411c-8929-4f1e9e5724f6.png">

**Comment by Krispkiwi** [comment]
> [custom-components/alexa_media_player#1683 (comment)](https://github.com/custom-components/alexa_media_player/issues/1683#issuecomment-1283797731)
> 
> Seems like Amazon changed something. Or there's an outage. But we're not alone

Are you from oceania by any chance? Noticing a trend of who the alexa issue is impacting in the other thread

**Comment by technowizard79** [comment]
> Alright, doesn't work anymore. Just failed again.
> 
> Fun fact, Announcement still works for me. You can switch to that as a workaround for now. 

Well I guess I'm a tiny bit relieved that it's not just my setup acting screwy... though of course that sucks for everyone else.  Wish they would just give HA/Node Red "official support," but we all know that'll never happen.  Yeah the Announcement thing was one of the features I mentioned above that still works.  Likewise, I suppose we can create routines with the needed TTS if this issue drags out.  The latter gets rid of the heads-up tone, if that's something people want to avoid.  I don't seem to have the Activity Log issue, so I wonder what that's about... Bezos needs to stop buying yachts, and actually hire some decent software developers already!

At this point I guess I just need to have patience, and let the "Counsel of Geniuses" do their thing...

**Comment by turbo2ltr** [comment]
Yeah I'm here trying to figure out why it's not working as well.  In the US.  I don't see any errors generated.  
Announcements are integral to the systems used to manage my ADD lol.

**Comment by bbindreiter** [comment]
> Yeah I'm here trying to figure out why it's not working as well. In the US. I don't see any errors generated. Announcements are integral to the systems used to manage my ADD lol.

Yes there is no error thrown. Nothing. Makes me think that it's an issue on their side.

**Comment by technowizard79** [comment]
Well it appears to be working again for me (for now) here in the US.  Looking more and more like it was just an issue/error on Amazon's side.  They were probably pushing out a server update, and someone forgot to carry a 1... :roll_eyes:

**Comment by turbo2ltr** [comment]
Still not working here.  Says it sent but nothing comes out..

**Comment by arthuraltino** [comment]
It's working here, but the `<audio src\>` tag that used do play audio urls isn't working anymore.

**Comment by bbindreiter** [comment]
Seems like it's back, thus closing this. Thanks everyone
