### ISSUE TITLE
Invalid or unexpected token

### ISSUE THREAD

**Issue by lowlyocean** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#9]
When using debug-level logging, nodered reports the following while trying to initialize Alexa. I'm not sure how to trace the "Invalid or unexpected token" error to a specific callstack:

```[warn] [alexa-remote-account:c969cb45.22f3d8] ENOENT: no such file or directory, open '.node-red/alexa_auth'
[info] [alexa-remote-account:c969cb45.22f3d8] intialising with the PROXY method and NO saved data...
[debug] [alexa-remote-account:c969cb45.22f3d8] Alexa-Remote: starting initialisation:
[debug] [alexa-remote-account:c969cb45.22f3d8] Alexa-Remote: {"authMethod":"proxy","initType":"proxy"}
[debug] [alexa-remote-account:c969cb45.22f3d8] Alexa-Remote: Use as User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
[debug] [alexa-remote-account:c969cb45.22f3d8] Alexa-Remote: Use as Login-Amazon-URL: amazon.com
[debug] [alexa-remote-account:c969cb45.22f3d8] Alexa-Remote: Use as Base-URL: pitangui.amazon.com
[debug] [alexa-remote-account:c969cb45.22f3d8] Alexa-Remote: No cookie given, generate one
[error] [alexa-remote-account:c969cb45.22f3d8] Invalid or unexpected token
```

Node-RED version: v2.0.5
Node.js  version: v14.17.5
Linux 5.10.17-v7+ arm LE

"node-red-contrib-alexa-remote2-applestrudel": {
  "version": "5.0.2",

"alexa-remote2": {
  "version": "3.9.0",

"alexa-cookie2": {
  "version": "3.4.3",

**Comment by bbindreiter** [comment]
Just to make sure: Have you fetched a token and saved it in the cookie-file?

**Comment by lowlyocean** [comment]
I've got the Account configured as such, and the file .node-red/alexa_auth is populated (probably with stale values):
![image](https://user-images.githubusercontent.com/13685818/129454819-cdf211e4-ccb3-4858-b01b-aea899b63102.png)

**Comment by bbindreiter** [comment]
Try host `layla.amazon.de` and page `amazon.de`. Language can stay.

**Comment by lowlyocean** [comment]
Thank you, unfortunately it produces the same result

**Comment by lowlyocean** [comment]
If I try to use Auth Method Cookie, there doesn't seem to be an issue. But as I understand, only the Proxy method would periodically refresh the cookie (as needed)?

**Comment by lowlyocean** [comment]
I was able to trace the callstack but *not* to the line that creates the message "Invalid or unexpected token" (maybe because of https://github.com/nodejs/node/issues/11865?)

```
Trace: Invalid or unexpected token
    at nodeError (/var/www/.node-red/node_modules/node-red-contrib-alexa-remote2-applestrudel/lib/common.js:371:17)
    at /var/www/.node-red/node_modules/node-red-contrib-alexa-remote2-applestrudel/lib/common.js:396:27
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by lowlyocean** [comment]
I was able to figure this out, my investigation is [documented here](https://discourse.nodered.org/t/stack-trace-for-syntaxerror-hides-the-actual-point-of-failure/50117). It turns out my copy of npm package _core-util-is_ had become corrupted and needed a reinstall.
