### ISSUE TITLE
Device Activity not working for some Alexa devices

### ISSUE THREAD

**Issue by xX-Nexus-Xx** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#90]
Hi, I really do love your node and have integrated it into my home control environment.

The "ON Device Activty" does work fine for my ECHO DOT and ECHO SHOW devices. Unfortunately, I cannot see any activty when giving same comands on

- my android phone using the Alexa app
- my ECHO CAR
- my FireTV

Any idea on how I can get this working ?

thanks for your help

**Comment by ChaiFox** [comment]
I have had the same issue as well, specifically with the device activity coming from my phone/tablet, the node to get echo devices does show them. It used to work at one point though.

**Comment by Robertou2** [comment]
Hi, I have the same issue, "ON Device Activity" works fine with the ECHO DOT devices but not with the android app. Did you find how I can get this working?

Thanks for your help
