### ISSUE TITLE
Init with proxy

### ISSUE THREAD

**Issue by pebl-hank** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#92]
So this worked fine for a while. All of the sudden I noticed today, that all nodes show "Init with proxy...". Initialization does not work. Re-authentication seems to be working, but results in the same "Init with proxy".
All log entry I get is
`
28 Oct 18:31:04 - [info] [alexa-remote-account:Amazon xxx] intialising "Amazon xxx" with the PROXY method and saved data...
`
Any ideas?

**Comment by cymplecy** [comment]
Same issue with me today :(

**Comment by mdte123** [comment]
Same for me.

**Comment by obaldius** [comment]
Same problem here, connected from Spain

**Comment by Amokd0c** [comment]
same here, connected from germany

**Comment by x-MaxG-x** [comment]
> same here, connected from germany Also the same, when i add a 2 behind "auth" in filename. Open IP:3456 in browser works, and I can enter username and password. but Open ... in browser is still visible...

Same for me here - the authentication in the browser looks like completed, but no file on disc is writen.
Two other accounts, which I use in parallel are still working fine - guess the stored cookie is still valid.

**Comment by Amokd0c** [comment]
> > same here, connected from germany Also the same, when i add a 2 behind "auth" in filename. Open IP:3456 in browser works, and I can enter username and password. but Open ... in browser is still visible...
> 
> Same for me here - the authentication in the browser looks like completed, but no file on disc is writen. Two other accounts, which I use in parallel are still working fine - guess the stored cookie is still valid.

Maybe it is a problem with the amazon servers?
Authentication works, but thats all
Is this the correct path of the auth file? /opt/iobroker/node_modules/iobroker.node-red 
My renamed file wasn´t placed there also

Mehr wie warten wird uns net übrig bleiben! :)
Mein 2tes auth file wurde nicht angelegt, deswegen bin ich mir net sicher ob das der richtige Pfad ist.
Stimmt der? Das bestehende hab ich auch noch nicht gelöscht...

**Comment by Tinbum1** [comment]
same for me in UK

**Comment by bbindreiter** [comment]
Will check tomorrow. Looks like they changed something that we're listening to when authenticating.

**Comment by biddster** [comment]
I had this. I jumped onto the my node-red box and bumped alexa-remote2 to the latest version and I'm back working. 

https://github.com/Apollon77/alexa-remote/releases/tag/v5.8.3

There's a fix "Fix retry issues for rate limited responses from amazon" which looks interesting.

**Comment by obaldius** [comment]
> I had this. I jumped onto the my node-red box and bumped alexa-remote2 to the latest version and I'm back working.
> 
> https://github.com/Apollon77/alexa-remote/releases/tag/v5.8.3
> 
> There's a fix in 5.8.3 `Fix retry issues for rate limited responses from amazon` which looks interesting.

Can you be more specific?

![image](https://user-images.githubusercontent.com/61756214/198753331-2eb5813b-64a4-4648-a0ed-abbab47e1d94.png)

Which archives did you replace with the newest version?

**Comment by Amokd0c** [comment]
the last release in the palett manager offers the 5.0.21 Version

**Comment by brunialti** [comment]
> So this worked fine for a while. All of the sudden I noticed today, that all nodes show "Init with proxy...". Initialization does not work. Re-authentication seems to be working, but results in the same "Init with proxy". All log entry I get is `28 Oct 18:31:04 - [info] [alexa-remote-account:Amazon xxx] intialising "Amazon xxx" with the PROXY method and saved data...` Any ideas?

Same for me in Italy.
I created a new alexa server.
After the login nothing happens for a while, that is the node is flashing the above message.
At this point if I try again to log in I get the error ERR_CONNECTION_RESET

**Comment by bbindreiter** [comment]
I am unable to reproduce the issue, it does work for me. Emptied my cookie file, Proxy Auth. After logging in the new cookie was written in the file. I am using `pitangui.amazon.com` 

Nevertheless, I am updating to the latest alexa-remote lib (5.8.3) and will publish a new version of applestrudel in a minute.

**Comment by x-MaxG-x** [comment]
Thank you for the fast reaction - I can confirm, that the update to 5.0.22 (lib 8.5.3) solved the issue for me.

**Comment by brunialti** [comment]
The new 5.0.22 version works correctly for me.

**Comment by pebl-hank** [comment]
Awesome, version bump worked fine. Thanks for the quick response!

**Comment by bbindreiter** [comment]
Good news, thanks! 👍

**Comment by pebl-hank** [comment]
Closing the issue.

**Comment by cymplecy** [comment]
update to 5.0.22 has fixed the issue for me also - thanks for quick response :)

**Comment by obaldius** [comment]
Working again. @bbindreiter took over this project to the next level, before him it used to fail way way more often, Thanks a lot for the lighthing fast response.

**Comment by bbindreiter** [comment]
Thank you but it's really @Apollon77 who does 99.99% of the work.

**Comment by dajuly20** [comment]
Had the same issues, also germany. Now soled with updating :)

**Comment by FrankGiesecke** [comment]
I had the same problem in Germany after leaving DST.
After updating from version 5.0.21 to version 5.0.22 everything works fine.

Thanks folks for your support.
