### ISSUE TITLE
Can not connect to server via Docker

### ISSUE THREAD

**Issue by Fr3d3rick83** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#93]
Hi,

I set everything up, but when I open the adress, the browser says "Can not connect".
https://i.ibb.co/RvzPhCD/Bildschirmfoto-2022-11-08-um-22-31-36.png

https://i.ibb.co/DMrJ8dv/Bildschirmfoto-2022-11-08-um-22-31-44.png

How can I connect to the port, when NR is running in a Docker container with IP like http://192.168.178.57:6335/

**Comment by stephenmetzger** [comment]
Are you running NodeRed in docker using a bridge network? Try using the host network if you can. This worked for me.
