### ISSUE TITLE
failed to load smarthome devices: "Cannot convert undefined or null to object"

### ISSUE THREAD

**Issue by peda** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#94]
Since this morning, I'm getting the following error message on initialisation:
`failed to load smarthome devices: "Cannot convert undefined or null to object"`

I'm using version `5.0.22` of `node-red-contrib-alexa-remote2-applestrudel`

All **existing** non-smart-home device related Alexa nodes are working properly. But the smart home device list is (obviously) empty and existing smart-home automations fail too.

Edit: I've tried to delete the credentials file and login again, but that didn't help either. Apart from the smart home device list, the initialisation is working fine (even when I restart node-red)

**Comment by peda** [comment]
I've now tried to add a get devices smart home node and this one worked - shortly afterwards the smart home device list re-appeared.

**Comment by Schnurp** [comment]
Can´t get it to work either. Same Message:

13.11.2022, 16:55:38[node: Amazon](http://192.168.1.15:1880/#)
msg : string[27]
"Initialisation was aborted!"

13.11.2022, 16:55:38[node: Amazon](http://192.168.1.15:1880/#)
msg : string[78]
"failed to load smarthome devices: "Cannot convert undefined or null to object""

**Comment by gnome4711** [comment]
same issue here!

not working since  3 or 4 days

**Comment by travelography** [comment]
Hi all, 
I think the problem here is related to my issue:
https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/issues/96

The device list seems not loadable as the API points on the wrong host.
