### ISSUE TITLE
No Body ends in full crash after updating to 5.0.23

### ISSUE THREAD

**Issue by travelography** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#96]
Hello,

I have since yesterday the problem that the Alexa remote nodes give a "no body" error message. Hopefully today I have installed the new update.

Unfortunately, it leads me to a complete failure of the Node Red installation with the following error message:

> 13 Nov 12:40:54 - [error] Error: no body
>     at handleResponse (/data/node_modules/alexa-remote2/alexa-remote.js:914:30)
>     at Gunzip.cb (/data/node_modules/alexa-remote2/alexa-remote.js:1029:37)
>     at Gunzip.zlibBufferOnEnd (node:zlib:161:10)
>     at Gunzip.emit (node:events:527:28)
>     at endReadableNT (node:internal/streams/readable:1345:12)

For a few seconds it is possible to open the web gui and the nodes have the status "init with proxiy":

![image](https://user-images.githubusercontent.com/16244070/201520088-cf9aaf36-a7d7-4d67-83e7-909f4a579b98.png)

The web console shows me different failed requests:
![image](https://user-images.githubusercontent.com/16244070/201520155-e3f193c1-559d-4227-b1c3-e90df3f665f3.png)

After the following failed request the whole installation crashes:
![image](https://user-images.githubusercontent.com/16244070/201520194-31653ba2-5f39-4219-9b2a-62bdc28e7321.png)

I am very happy to receive feedback and am available for further error analysis. 

Best regards
Chris

**Comment by bbindreiter** [comment]
Interesting, I hope I didn't rate limit the calls during initializing. I haven't checked that case on my installation tbh (had a working cookie set already). If it works then I doubt it's from 5.0.23. 

Thanks, I will check it later today asap.

**Comment by travelography** [comment]
Thank you @bbindreiter for your quick reply. 

It seems to me that my configuration is not compatible with the current version. 

After deleting my configuration node with the account settings, at least my Node Red installation no longer crashes. Puuuh ;-) I also control the night light with it.

Maybe it will help you if you post here my configuration from the Node Red backup:

`    {
        "id": "...",
        "type": "alexa-remote-account",
        "name": "",
        "authMethod": "proxy",
        "proxyOwnIp": "....",
        "proxyPort": "34565",
        "cookieFile": "/usr/src/node-red/authfile",
        "refreshInterval": "2",
        "alexaServiceHost": "layla.amazon.de",
        "amazonPage": "amazon.de",
        "acceptLanguage": "de-DE",
        "onKeywordInLanguage": "",
        "userAgent": "",
        "useWsMqtt": "on",
        "autoInit": "on"
    },`

**Comment by bbindreiter** [comment]
Sorry, just to understand. Does a fresh configuration node work for you?

**Comment by travelography** [comment]
Nope and sorry for beeing not clear enough.
As soon as I enter my credentials, node red crashs and logs the message from my first post.

**Comment by bbindreiter** [comment]
Hello, I tried to reproduce it but failed.

Here's what I did:
- Deleted my associated account and emptied the stored cookie file
- Redeployed -> All Alexa Nodes complaining about missing account
- Went into the details of one of them -> Add new account with all the settings -> Save
- Full redeploy -> got the hint to open browser at xxx:3456
- After successfull auth nothing happened, I suspect because something was cached (I did not have to enter my Amazon credentials, got the success page immadiately)
- Node Red restart
- open browser at xxx:3456 -> Auth with 2FA -> Maybe 10s after successful auth the cookie was written in the file
- Had to set the Account in all Alexa Nodes to the new one
- Redeploy and all worked fine again

**Comment by travelography** [comment]
Hello @bbindreiter,

thank you very much for your efforts. 

I can recreate the error by installing Node Red  with version 3.0.2 in a Docker container. 

In the empty installation I deployed your latest version 5.0.23. 

As soon as I create an account and enter the credentials as named above, Node Red crashes.

**Comment by travelography** [comment]
My steps:

- Install & Deploy Node Red 3.02.
- node-red admin install node-red-contrib-alexa-remote2-applestrudel@5.0.23
- add initialise to an empty flow
- add alexa account as configuration node
- full deploy
- enter credentials in browser
- add further alexa node
- full deploy
- system crash

**Comment by travelography** [comment]
I did further research and tried the following things:

1. downgrade to an earlier version (5.0.22 / 5.0.21 / 5.0.10) -> same error. 
2. the code line 914 in alexa-remote.js generates an error which is probably not caught correctly 

I seem to have mistakenly thought it came with the update. Everything ran smoothly before the update and otherwise no updates or changes were made in Node Red. In my production Node Red, the cookie file is also still filled. 

As soon as I enter my Amazon credentials and the response is processed, the system crashes (prod and test environment). 

Does the response depend on the browser in which the authentication is performed (blocking third party cookies, etc.)?

**Comment by bbindreiter** [comment]
Probably. It seems as if you're getting a http 500 error back from Amazon. This could have various reasons. If you're up for it, add log output of the entire response and see if there's any additional information in the response body.

**Comment by travelography** [comment]
You are right! I get a few 200 and then suddenly a request gets 503. I will try to figure out which url is requested and causes the problem

> Response: 200
> 
> now happens the error
> 
> 503
> 
> SyntaxError: Unexpected token < in JSON at position 0
> 
>     at JSON.parse (<anonymous>)
> 
>     at handleResponse (/usr/src/node-red/node_modules/alexa-remote2/alexa-remote.js:910:28)
> 
>     at Gunzip.cb (/usr/src/node-red/node_modules/alexa-remote2/alexa-remote.js:1035:37)
> 
>     at Gunzip.zlibBufferOnEnd (node:zlib:161:10)
> 
>     at Gunzip.emit (node:events:527:28)
> 
>     at endReadableNT (node:internal/streams/readable:1345:12)
> 
>     at processTicksAndRejections (node:internal/process/task_queues:83:21)
> 
> <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
> 
> <html xmlns="http://www.w3.org/1999/xhtml">
> 
> <head>
> 
> <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
> 
> <title>Website Temporarily Unavailable</title>
> 
> </head>
> 
> 
> 
> <body>
> 
> <p>&nbsp;</p>
> 
> <center><img src="http://g-ecx.images-amazon.com/images/G/01/website/errors/503/generic.png" alt="website temporarily unavailable" width="500" height="300"></center>
> 
> </body>
> 
> 
> 
> </html>

**Comment by travelography** [comment]
The get request on /api/devices-v2/device?cached=true&_=1668421318677  fails.

**Comment by travelography** [comment]
I get a full list of all my devices with the URL https://alexa.amazon.com/api/devices-v2/device 

Do you have an idea how to manually change it?

**Comment by bbindreiter** [comment]
> 

I honestly have no idea where this url comes from and why the response cannot be parsed. It's probably also some error response. Sorry, I don't have the time at the moment to debug this, it's pretty time consuming. All I can say for now is that the fetching works for me, I even tried to penetrate the endpoint for a few minutes.

**Comment by bbindreiter** [comment]
Maybe @Apollon77 has an idea. 🤔

**Comment by Apollon77** [comment]
I would need a full debug logging of such a signup process. öot send to iobroker@fischer-ka.de

**Comment by travelography** [comment]
> > 
> 
> I honestly have no idea where this url comes from and why the response cannot be parsed. It's probably also some error response. Sorry, I don't have the time at the moment to debug this, it's pretty time consuming. All I can say for now is that the fetching works for me, I even tried to penetrate the endpoint for a few minutes.

The code expects JSON and repsonse delivers a HTML document that the website is currently not available. 



> I would need a full debug logging of such a signup process. pot send to [iobroker@fischer-ka.de](mailto:iobroker@fischer-ka.de)

Could you please give me a hint on how to generate the debug log. 

Currently, in the alexa-remote.js, I have changed part of the code from this._options.logger && this._options.logger to console.log to get the output in the Portainer Console as I have Node Red running in Docker Container. 

Is there any other easier way? 

Anyway, thank you very much for your help!

**Comment by Apollon77** [comment]
Logging wise I wpuld need "proxyLogLevel"= debug when initializing alexa-remote, Then a lot of log will come to console log/the logger
