### ISSUE TITLE
Message:"Too many requests. Try again in some time."

### ISSUE THREAD

**Issue by 19dexter86** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#97]
When starting a "GET" query, the error message "too many requests" appears when selecting "DEVICES".
With the other options "GROUPS, DEFINITIONS, etc" everything works.

With an "ACTION" node no devices are found. Only "???".

I use 5.0.23

**Comment by bbindreiter** [comment]
The get and set requests were rate limited. Only 1 request per 5 minutes.

**Comment by 19dexter86** [comment]
Ok but i dont do this. First try and i got this error.
My node for control a device give me the error  "failed to load smarthome devices: cannot convert undefined or null to object"
Then i tried an Get Device and the error Too many request appeard. 
Now the next day i tried again and same result.
I make a new authentication node and a new cookie. Not worked for me.
